/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  CartResponse,
  CreateCartBody,
  CreateCartParams,
  GetCartParams,
  NotFoundResponse
} from '.././schema';
import { customInstance } from '../../config/custom-instance';
import type { BodyType } from '../../config/custom-instance';

/**
 * Creates a new cart.

**Please be aware**; The `token` value found in the response body is used to authorize all future operations on this cart through the Auth API Key `X-Spree-Order-Token`.
 * @summary Create a Cart
 */
export const createCart = (
  createCartBody?: BodyType<CreateCartBody>,
  params?: CreateCartParams
) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart`,
    method: 'POST',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: createCartBody,
    params
  });
};

export const getCreateCartMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCart>>,
    TError,
    { data: BodyType<CreateCartBody>; params?: CreateCartParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCart>>,
  TError,
  { data: BodyType<CreateCartBody>; params?: CreateCartParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCart>>,
    { data: BodyType<CreateCartBody>; params?: CreateCartParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return createCart(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCartMutationResult = NonNullable<Awaited<ReturnType<typeof createCart>>>;
export type CreateCartMutationBody = BodyType<CreateCartBody>;
export type CreateCartMutationError = unknown;

/**
 * @summary Create a Cart
 */
export const useCreateCart = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCart>>,
    TError,
    { data: BodyType<CreateCartBody>; params?: CreateCartParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof createCart>>,
  TError,
  { data: BodyType<CreateCartBody>; params?: CreateCartParams },
  TContext
> => {
  const mutationOptions = getCreateCartMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Deletes a specified cart.

When this endpoint is successfully executed, all shipments are cancelled, payments are voided, then line items, shipments & payments are all deleted.
 * @summary Delete a Cart
 */
export const deletesCart = () => {
  return customInstance<void>({ url: `/api/v2/storefront/cart`, method: 'DELETE' });
};

export const getDeletesCartMutationOptions = <
  TError = NotFoundResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deletesCart>>, TError, void, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof deletesCart>>, TError, void, TContext> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletesCart>>, void> = () => {
    return deletesCart();
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletesCartMutationResult = NonNullable<Awaited<ReturnType<typeof deletesCart>>>;

export type DeletesCartMutationError = NotFoundResponse;

/**
 * @summary Delete a Cart
 */
export const useDeletesCart = <TError = NotFoundResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deletesCart>>, TError, void, TContext>;
}): UseMutationResult<Awaited<ReturnType<typeof deletesCart>>, TError, void, TContext> => {
  const mutationOptions = getDeletesCartMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Returns the cart for the current user.
 * @summary Retrieve a Cart
 */
export const getCart = (params?: GetCartParams, signal?: AbortSignal) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart`,
    method: 'GET',
    params,
    signal
  });
};

export const getGetCartQueryKey = (params?: GetCartParams) => {
  return [`/api/v2/storefront/cart`, ...(params ? [params] : [])] as const;
};

export const getGetCartQueryOptions = <
  TData = Awaited<ReturnType<typeof getCart>>,
  TError = NotFoundResponse
>(
  params?: GetCartParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCartQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCart>>> = ({ signal }) =>
    getCart(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCart>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCartQueryResult = NonNullable<Awaited<ReturnType<typeof getCart>>>;
export type GetCartQueryError = NotFoundResponse;

/**
 * @summary Retrieve a Cart
 */
export const useGetCart = <TData = Awaited<ReturnType<typeof getCart>>, TError = NotFoundResponse>(
  params?: GetCartParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>> }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCartQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetCartSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCart>>,
  TError = NotFoundResponse
>(
  params?: GetCartParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCartQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCart>>> = ({ signal }) =>
    getCart(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCart>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCartSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getCart>>>;
export type GetCartSuspenseQueryError = NotFoundResponse;

/**
 * @summary Retrieve a Cart
 */
export const useGetCartSuspense = <
  TData = Awaited<ReturnType<typeof getCart>>,
  TError = NotFoundResponse
>(
  params?: GetCartParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCartSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
