/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  CartResponse,
  NotFoundResponse,
  SelectShippingMethodBody,
  SelectShippingMethodParams,
  ShipmentResponse,
  UnprocessableEntityResponse
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';
import type { BodyType } from '../../../config/custom-instance';

/**
 * Selects shipping method for Shipment(s).

To generate shipments you first need to fetch shipping rates via

[Get Shipping Rates](https://api.spreecommerce.org/docs/api-v2/b3A6MzE0Mjc2MQ-list-shipping-rates) endpoint
 * @summary Selects shipping method for shipment(s)
 */
export const selectShippingMethod = (
  selectShippingMethodBody: BodyType<SelectShippingMethodBody>,
  params?: SelectShippingMethodParams
) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/checkout/select_shipping_method`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: selectShippingMethodBody,
    params
  });
};

export const getSelectShippingMethodMutationOptions = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof selectShippingMethod>>,
    TError,
    { data: BodyType<SelectShippingMethodBody>; params?: SelectShippingMethodParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof selectShippingMethod>>,
  TError,
  { data: BodyType<SelectShippingMethodBody>; params?: SelectShippingMethodParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof selectShippingMethod>>,
    { data: BodyType<SelectShippingMethodBody>; params?: SelectShippingMethodParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return selectShippingMethod(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type SelectShippingMethodMutationResult = NonNullable<
  Awaited<ReturnType<typeof selectShippingMethod>>
>;
export type SelectShippingMethodMutationBody = BodyType<SelectShippingMethodBody>;
export type SelectShippingMethodMutationError = NotFoundResponse | UnprocessableEntityResponse;

/**
 * @summary Selects shipping method for shipment(s)
 */
export const useSelectShippingMethod = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof selectShippingMethod>>,
    TError,
    { data: BodyType<SelectShippingMethodBody>; params?: SelectShippingMethodParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof selectShippingMethod>>,
  TError,
  { data: BodyType<SelectShippingMethodBody>; params?: SelectShippingMethodParams },
  TContext
> => {
  const mutationOptions = getSelectShippingMethodMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Returns a list of available shipping rates for the checkout.

Shipping rates are grouped against shipments. Each checkout can have multiple shipments. Some products are in stock and will be shipped immediately, while others might be back-ordered and sent later.
 * @summary List Shipping Rates
 */
export const shippingRates = (signal?: AbortSignal) => {
  return customInstance<ShipmentResponse>({
    url: `/api/v2/storefront/checkout/shipping_rates`,
    method: 'GET',
    signal
  });
};

export const getShippingRatesQueryKey = () => {
  return [`/api/v2/storefront/checkout/shipping_rates`] as const;
};

export const getShippingRatesQueryOptions = <
  TData = Awaited<ReturnType<typeof shippingRates>>,
  TError = NotFoundResponse
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shippingRates>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShippingRatesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shippingRates>>> = ({ signal }) =>
    shippingRates(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shippingRates>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShippingRatesQueryResult = NonNullable<Awaited<ReturnType<typeof shippingRates>>>;
export type ShippingRatesQueryError = NotFoundResponse;

/**
 * @summary List Shipping Rates
 */
export const useShippingRates = <
  TData = Awaited<ReturnType<typeof shippingRates>>,
  TError = NotFoundResponse
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shippingRates>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShippingRatesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getShippingRatesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof shippingRates>>,
  TError = NotFoundResponse
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof shippingRates>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShippingRatesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shippingRates>>> = ({ signal }) =>
    shippingRates(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof shippingRates>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShippingRatesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof shippingRates>>
>;
export type ShippingRatesSuspenseQueryError = NotFoundResponse;

/**
 * @summary List Shipping Rates
 */
export const useShippingRatesSuspense = <
  TData = Awaited<ReturnType<typeof shippingRates>>,
  TError = NotFoundResponse
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof shippingRates>>, TError, TData>
  >;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShippingRatesSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
