/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Authentication
 * Spree uses oAuth based Authentication via short-lived Bearer tokens. You can either create a new one or refresh existing token.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';
import type { CreateOrRefreshTokenBodyOne, CreateOrRefreshTokenBodyTwo, Token } from '.././schema';
import { customInstance } from '../../../config/custom-instance';
import type { BodyType } from '../../../config/custom-instance';

/**
 * This endpoint creates a new Bearer Token or refreshes an existing Bearer Token.

The `token` found in the response body is required to authorize API calls.
 * @summary Create or Refresh a Token
 */
export const createOrRefreshToken = (
  createOrRefreshTokenBody:
    | BodyType<CreateOrRefreshTokenBodyOne | CreateOrRefreshTokenBodyTwo>
    | CreateOrRefreshTokenBodyTwo
) => {
  return customInstance<Token>({
    url: `/spree_oauth/token`,
    method: 'POST',
    data: createOrRefreshTokenBody
  });
};

export const getCreateOrRefreshTokenMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOrRefreshToken>>,
    TError,
    { data: BodyType<CreateOrRefreshTokenBodyOne | CreateOrRefreshTokenBodyTwo> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOrRefreshToken>>,
  TError,
  { data: BodyType<CreateOrRefreshTokenBodyOne | CreateOrRefreshTokenBodyTwo> },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOrRefreshToken>>,
    { data: BodyType<CreateOrRefreshTokenBodyOne | CreateOrRefreshTokenBodyTwo> }
  > = (props) => {
    const { data } = props ?? {};

    return createOrRefreshToken(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOrRefreshTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOrRefreshToken>>
>;
export type CreateOrRefreshTokenMutationBody = BodyType<
  CreateOrRefreshTokenBodyOne | CreateOrRefreshTokenBodyTwo
>;
export type CreateOrRefreshTokenMutationError = unknown;

/**
 * @summary Create or Refresh a Token
 */
export const useCreateOrRefreshToken = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOrRefreshToken>>,
    TError,
    { data: BodyType<CreateOrRefreshTokenBodyOne | CreateOrRefreshTokenBodyTwo> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof createOrRefreshToken>>,
  TError,
  { data: BodyType<CreateOrRefreshTokenBodyOne | CreateOrRefreshTokenBodyTwo> },
  TContext
> => {
  const mutationOptions = getCreateOrRefreshTokenMutationOptions(options);

  return useMutation(mutationOptions);
};
