/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  AddressListResponse,
  AddressResponse,
  AddressesListParams,
  CreateAddressBody,
  CreateAddressParams,
  ForbiddenResponse,
  NotFoundResponse,
  UpdateAddressBody,
  UpdateAddressParams
} from '.././schema';
import { customInstance } from '../../config/custom-instance';
import type { BodyType } from '../../config/custom-instance';

/**
 * Returns a list of addresses for the current user.
 * @summary List all Addresses
 */
export const addressesList = (params?: AddressesListParams, signal?: AbortSignal) => {
  return customInstance<AddressListResponse>({
    url: `/api/v2/storefront/account/addresses`,
    method: 'GET',
    params,
    signal
  });
};

export const getAddressesListQueryKey = (params?: AddressesListParams) => {
  return [`/api/v2/storefront/account/addresses`, ...(params ? [params] : [])] as const;
};

export const getAddressesListQueryOptions = <
  TData = Awaited<ReturnType<typeof addressesList>>,
  TError = ForbiddenResponse
>(
  params?: AddressesListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addressesList>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAddressesListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addressesList>>> = ({ signal }) =>
    addressesList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof addressesList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AddressesListQueryResult = NonNullable<Awaited<ReturnType<typeof addressesList>>>;
export type AddressesListQueryError = ForbiddenResponse;

/**
 * @summary List all Addresses
 */
export const useAddressesList = <
  TData = Awaited<ReturnType<typeof addressesList>>,
  TError = ForbiddenResponse
>(
  params?: AddressesListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addressesList>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAddressesListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAddressesListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof addressesList>>,
  TError = ForbiddenResponse
>(
  params?: AddressesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof addressesList>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAddressesListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addressesList>>> = ({ signal }) =>
    addressesList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof addressesList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AddressesListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof addressesList>>
>;
export type AddressesListSuspenseQueryError = ForbiddenResponse;

/**
 * @summary List all Addresses
 */
export const useAddressesListSuspense = <
  TData = Awaited<ReturnType<typeof addressesList>>,
  TError = ForbiddenResponse
>(
  params?: AddressesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof addressesList>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAddressesListSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Creates a new address for the current user.
 * @summary Create an Address
 */
export const createAddress = (
  createAddressBody: BodyType<CreateAddressBody>,
  params?: CreateAddressParams
) => {
  return customInstance<AddressResponse>({
    url: `/api/v2/storefront/account/addresses`,
    method: 'POST',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: createAddressBody,
    params
  });
};

export const getCreateAddressMutationOptions = <
  TError = ForbiddenResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAddress>>,
    TError,
    { data: BodyType<CreateAddressBody>; params?: CreateAddressParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAddress>>,
  TError,
  { data: BodyType<CreateAddressBody>; params?: CreateAddressParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAddress>>,
    { data: BodyType<CreateAddressBody>; params?: CreateAddressParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return createAddress(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAddressMutationResult = NonNullable<Awaited<ReturnType<typeof createAddress>>>;
export type CreateAddressMutationBody = BodyType<CreateAddressBody>;
export type CreateAddressMutationError = ForbiddenResponse;

/**
 * @summary Create an Address
 */
export const useCreateAddress = <TError = ForbiddenResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAddress>>,
    TError,
    { data: BodyType<CreateAddressBody>; params?: CreateAddressParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof createAddress>>,
  TError,
  { data: BodyType<CreateAddressBody>; params?: CreateAddressParams },
  TContext
> => {
  const mutationOptions = getCreateAddressMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * This endpoint removes the specified address for the current user. It uses a soft delete to retain address information for pre-existing orders.
 * @summary Remove an Address
 */
export const removeAddress = (id: string) => {
  return customInstance<void>({
    url: `/api/v2/storefront/account/addresses/${id}`,
    method: 'DELETE'
  });
};

export const getRemoveAddressMutationOptions = <
  TError = NotFoundResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeAddress>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeAddress>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeAddress>>, { id: string }> = (
    props
  ) => {
    const { id } = props ?? {};

    return removeAddress(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveAddressMutationResult = NonNullable<Awaited<ReturnType<typeof removeAddress>>>;

export type RemoveAddressMutationError = NotFoundResponse;

/**
 * @summary Remove an Address
 */
export const useRemoveAddress = <TError = NotFoundResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeAddress>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeAddress>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getRemoveAddressMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Updates the specified address for the current user.
 * @summary Update an Address
 */
export const updateAddress = (
  id: string,
  updateAddressBody: BodyType<UpdateAddressBody>,
  params?: UpdateAddressParams
) => {
  return customInstance<AddressResponse>({
    url: `/api/v2/storefront/account/addresses/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: updateAddressBody,
    params
  });
};

export const getUpdateAddressMutationOptions = <
  TError = ForbiddenResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAddress>>,
    TError,
    { id: string; data: BodyType<UpdateAddressBody>; params?: UpdateAddressParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAddress>>,
  TError,
  { id: string; data: BodyType<UpdateAddressBody>; params?: UpdateAddressParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAddress>>,
    { id: string; data: BodyType<UpdateAddressBody>; params?: UpdateAddressParams }
  > = (props) => {
    const { id, data, params } = props ?? {};

    return updateAddress(id, data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAddressMutationResult = NonNullable<Awaited<ReturnType<typeof updateAddress>>>;
export type UpdateAddressMutationBody = BodyType<UpdateAddressBody>;
export type UpdateAddressMutationError = ForbiddenResponse;

/**
 * @summary Update an Address
 */
export const useUpdateAddress = <TError = ForbiddenResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAddress>>,
    TError,
    { id: string; data: BodyType<UpdateAddressBody>; params?: UpdateAddressParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateAddress>>,
  TError,
  { id: string; data: BodyType<UpdateAddressBody>; params?: UpdateAddressParams },
  TContext
> => {
  const mutationOptions = getUpdateAddressMutationOptions(options);

  return useMutation(mutationOptions);
};
