/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/spree_oauth/token': {
    /**
     * Create or Refresh a Token
     * @description This endpoint creates a new Bearer Token or refreshes an existing Bearer Token.
     *
     * The `token` found in the response body is required to authorize API calls.
     */
    post: operations['create-or-refresh-token'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Token: {
      /** @example 2480c16561d1391ea81ca5336b651e9a29f4524f6dee8c7f3f02a600159189c3 */
      access_token: string;
      /**
       * @default Bearer
       * @example Bearer
       */
      token_type: string;
      /**
       * @description Time (in seconds) after which the access token will expire
       * @example 7200
       */
      expires_in: number;
      /** @example f5d78642252eeb3f3001f67b196ac21a27afc030462a54060b0ebbdae2b8dc9c */
      refresh_token: string;
      /**
       * @default admin
       * @example admin
       */
      scope?: string;
      /** @example 1539863418 */
      created_at: number;
    };
    /** Create a new token (grant_type: password) */
    CreateTokenBody: {
      /**
       * @example password
       * @enum {string}
       */
      grant_type: 'password';
      /**
       * @description User email address
       * @example spree@example.com
       */
      username: string;
      /**
       * @description User password
       * @example spree123
       */
      password: string;
      /**
       * @description Pass the value `admin` to create a Platform User Token, allowing access to the Platform API.
       * @enum {string|null}
       */
      scope?: 'admin' | null;
    };
    /** Create a new token (grant_type: client_credentials) */
    ClientTokenBody: {
      /**
       * @example client_credentials
       * @enum {string}
       */
      grant_type: 'client_credentials';
      /**
       * @description Use the client id
       * @example 27af95fd57a424e5d01aaf5eab
       */
      client_id: string;
      /**
       * @description Client secret key.
       * @example 1324a8d5c0ca57daf384fae39f811a5144330143301'
       */
      client_secret: string;
    };
    /** Refresh an existing token (grant_type: refresh_token) */
    RefreshTokenBody: {
      /**
       * @example refresh_token
       * @enum {string}
       */
      grant_type: 'refresh_token';
      /**
       * @description Refresh token obtained from the create token response
       * @example 27af95fd57a424e5d01aaf5eab1324a8d5c0ca57daf384fae39f811a5144330143301'
       */
      refresh_token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Create or Refresh a Token
   * @description This endpoint creates a new Bearer Token or refreshes an existing Bearer Token.
   *
   * The `token` found in the response body is required to authorize API calls.
   */
  'create-or-refresh-token': {
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['CreateTokenBody']
          | components['schemas']['ClientTokenBody']
          | components['schemas']['RefreshTokenBody'];
        'application/xml': Record<string, never>;
      };
    };
    responses: {
      /** @description Token was successfully created or refreshed. */
      200: {
        content: {
          'application/json': components['schemas']['Token'];
        };
      };
    };
  };
}
