/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  NotFoundResponse,
  ShowTaxonParams,
  TaxonListResponse,
  TaxonResponse,
  TaxonsListParams
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';

/**
 * Returns a list of Taxons. [Read more about Taxons](/developer/core-concepts/products#taxons-and-taxonomies)
 * @summary List all Taxons
 */
export const taxonsList = (params?: TaxonsListParams, signal?: AbortSignal) => {
  return customInstance<TaxonListResponse>({
    url: `/api/v2/storefront/taxons`,
    method: 'GET',
    params,
    signal
  });
};

export const getTaxonsListQueryKey = (params?: TaxonsListParams) => {
  return [`/api/v2/storefront/taxons`, ...(params ? [params] : [])] as const;
};

export const getTaxonsListQueryOptions = <
  TData = Awaited<ReturnType<typeof taxonsList>>,
  TError = unknown
>(
  params?: TaxonsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof taxonsList>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTaxonsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof taxonsList>>> = ({ signal }) =>
    taxonsList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof taxonsList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TaxonsListQueryResult = NonNullable<Awaited<ReturnType<typeof taxonsList>>>;
export type TaxonsListQueryError = unknown;

/**
 * @summary List all Taxons
 */
export const useTaxonsList = <TData = Awaited<ReturnType<typeof taxonsList>>, TError = unknown>(
  params?: TaxonsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof taxonsList>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTaxonsListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getTaxonsListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof taxonsList>>,
  TError = unknown
>(
  params?: TaxonsListParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof taxonsList>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTaxonsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof taxonsList>>> = ({ signal }) =>
    taxonsList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof taxonsList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TaxonsListSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof taxonsList>>>;
export type TaxonsListSuspenseQueryError = unknown;

/**
 * @summary List all Taxons
 */
export const useTaxonsListSuspense = <
  TData = Awaited<ReturnType<typeof taxonsList>>,
  TError = unknown
>(
  params?: TaxonsListParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof taxonsList>>, TError, TData>>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTaxonsListSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Returns the details of a specified taxon.
 * @summary Retrieve a Taxon
 */
export const showTaxon = (
  taxonPermalink: string,
  params?: ShowTaxonParams,
  signal?: AbortSignal
) => {
  return customInstance<TaxonResponse>({
    url: `/api/v2/storefront/taxons/${taxonPermalink}`,
    method: 'GET',
    params,
    signal
  });
};

export const getShowTaxonQueryKey = (taxonPermalink: string, params?: ShowTaxonParams) => {
  return [`/api/v2/storefront/taxons/${taxonPermalink}`, ...(params ? [params] : [])] as const;
};

export const getShowTaxonQueryOptions = <
  TData = Awaited<ReturnType<typeof showTaxon>>,
  TError = NotFoundResponse
>(
  taxonPermalink: string,
  params?: ShowTaxonParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof showTaxon>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShowTaxonQueryKey(taxonPermalink, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showTaxon>>> = ({ signal }) =>
    showTaxon(taxonPermalink, params, signal);

  return { queryKey, queryFn, enabled: !!taxonPermalink, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof showTaxon>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShowTaxonQueryResult = NonNullable<Awaited<ReturnType<typeof showTaxon>>>;
export type ShowTaxonQueryError = NotFoundResponse;

/**
 * @summary Retrieve a Taxon
 */
export const useShowTaxon = <
  TData = Awaited<ReturnType<typeof showTaxon>>,
  TError = NotFoundResponse
>(
  taxonPermalink: string,
  params?: ShowTaxonParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof showTaxon>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShowTaxonQueryOptions(taxonPermalink, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getShowTaxonSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof showTaxon>>,
  TError = NotFoundResponse
>(
  taxonPermalink: string,
  params?: ShowTaxonParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof showTaxon>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShowTaxonQueryKey(taxonPermalink, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showTaxon>>> = ({ signal }) =>
    showTaxon(taxonPermalink, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!taxonPermalink,
    ...queryOptions
  } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof showTaxon>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type ShowTaxonSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof showTaxon>>>;
export type ShowTaxonSuspenseQueryError = NotFoundResponse;

/**
 * @summary Retrieve a Taxon
 */
export const useShowTaxonSuspense = <
  TData = Awaited<ReturnType<typeof showTaxon>>,
  TError = NotFoundResponse
>(
  taxonPermalink: string,
  params?: ShowTaxonParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof showTaxon>>, TError, TData>>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShowTaxonSuspenseQueryOptions(taxonPermalink, params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
