/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  ForbiddenResponse,
  GetDigitals200Eight,
  GetDigitals200Five,
  GetDigitals200Four,
  GetDigitals200Nine,
  GetDigitals200One,
  GetDigitals200Onefive,
  GetDigitals200Onefour,
  GetDigitals200Oneone,
  GetDigitals200Onethree,
  GetDigitals200Onetwo,
  GetDigitals200Onezero,
  GetDigitals200Seven,
  GetDigitals200Six,
  GetDigitals200Three,
  GetDigitals200Two
} from '.././schema';
import { customInstance } from '../../config/custom-instance';

/**
 * This endpoint allows you to download a digital item using the unique digital_link token.

The digital_link token value can be found by including `line_items.digital_links` in a completed order lookup.

Use the **Retrieve an Order Status** endpoint found under the Order Status tab, or the **Retrieve an Order** endpoint found under the Account / Orders tab to perform a completed order lookup.

Depending on the store that the item was purchased in, downloads may be restricted to a set number of days since the purchase was made. Additionally, the number of times a download link can be used may be restricted.

If you are not authorized to perform the download due to the download limit restrictions mentioned above, a 403 response will be returned.
 * @summary Download a Digital Asset
 */
export const getDigitals = (token: string, signal?: AbortSignal) => {
  return customInstance<
    | GetDigitals200One
    | GetDigitals200Two
    | GetDigitals200Three
    | GetDigitals200Four
    | GetDigitals200Five
    | GetDigitals200Six
    | GetDigitals200Seven
    | GetDigitals200Eight
    | GetDigitals200Nine
    | GetDigitals200Onezero
    | GetDigitals200Oneone
    | GetDigitals200Onetwo
    | GetDigitals200Onethree
    | GetDigitals200Onefour
    | GetDigitals200Onefive
  >({ url: `/api/v2/storefront/digitals/${token}`, method: 'GET', signal });
};

export const getGetDigitalsQueryKey = (token: string) => {
  return [`/api/v2/storefront/digitals/${token}`] as const;
};

export const getGetDigitalsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDigitals>>,
  TError = ForbiddenResponse
>(
  token: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDigitals>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDigitalsQueryKey(token);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDigitals>>> = ({ signal }) =>
    getDigitals(token, signal);

  return { queryKey, queryFn, enabled: !!token, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDigitals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDigitalsQueryResult = NonNullable<Awaited<ReturnType<typeof getDigitals>>>;
export type GetDigitalsQueryError = ForbiddenResponse;

/**
 * @summary Download a Digital Asset
 */
export const useGetDigitals = <
  TData = Awaited<ReturnType<typeof getDigitals>>,
  TError = ForbiddenResponse
>(
  token: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDigitals>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetDigitalsQueryOptions(token, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetDigitalsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getDigitals>>,
  TError = ForbiddenResponse
>(
  token: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDigitals>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDigitalsQueryKey(token);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDigitals>>> = ({ signal }) =>
    getDigitals(token, signal);

  return { queryKey, queryFn, enabled: !!token, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getDigitals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDigitalsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getDigitals>>>;
export type GetDigitalsSuspenseQueryError = ForbiddenResponse;

/**
 * @summary Download a Digital Asset
 */
export const useGetDigitalsSuspense = <
  TData = Awaited<ReturnType<typeof getDigitals>>,
  TError = ForbiddenResponse
>(
  token: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDigitals>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetDigitalsSuspenseQueryOptions(token, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
