/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  CreateWishlistBody,
  CreateWishlistParams,
  ForbiddenResponse,
  GetDefaultWishlistParams,
  GetWishlistDetailsParams,
  ListWishlistsForCurrentUserParams,
  UnprocessableEntityResponse,
  UpdateWishlistBody,
  UpdateWishlistParams,
  WishlistListResponse,
  WishlistResponse
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';
import type { BodyType } from '../../../config/custom-instance';

/**
 * Returns all wishlists available to the current user, in the current store.
 * @summary List all Wishlists
 */
export const listWishlistsForCurrentUser = (
  params?: ListWishlistsForCurrentUserParams,
  signal?: AbortSignal
) => {
  return customInstance<WishlistListResponse>({
    url: `/api/v2/storefront/wishlists`,
    method: 'GET',
    params,
    signal
  });
};

export const getListWishlistsForCurrentUserQueryKey = (
  params?: ListWishlistsForCurrentUserParams
) => {
  return [`/api/v2/storefront/wishlists`, ...(params ? [params] : [])] as const;
};

export const getListWishlistsForCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof listWishlistsForCurrentUser>>,
  TError = ForbiddenResponse
>(
  params?: ListWishlistsForCurrentUserParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listWishlistsForCurrentUser>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListWishlistsForCurrentUserQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listWishlistsForCurrentUser>>> = ({
    signal
  }) => listWishlistsForCurrentUser(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listWishlistsForCurrentUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListWishlistsForCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof listWishlistsForCurrentUser>>
>;
export type ListWishlistsForCurrentUserQueryError = ForbiddenResponse;

/**
 * @summary List all Wishlists
 */
export const useListWishlistsForCurrentUser = <
  TData = Awaited<ReturnType<typeof listWishlistsForCurrentUser>>,
  TError = ForbiddenResponse
>(
  params?: ListWishlistsForCurrentUserParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listWishlistsForCurrentUser>>, TError, TData>
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getListWishlistsForCurrentUserQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getListWishlistsForCurrentUserSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listWishlistsForCurrentUser>>,
  TError = ForbiddenResponse
>(
  params?: ListWishlistsForCurrentUserParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listWishlistsForCurrentUser>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListWishlistsForCurrentUserQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listWishlistsForCurrentUser>>> = ({
    signal
  }) => listWishlistsForCurrentUser(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listWishlistsForCurrentUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListWishlistsForCurrentUserSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listWishlistsForCurrentUser>>
>;
export type ListWishlistsForCurrentUserSuspenseQueryError = ForbiddenResponse;

/**
 * @summary List all Wishlists
 */
export const useListWishlistsForCurrentUserSuspense = <
  TData = Awaited<ReturnType<typeof listWishlistsForCurrentUser>>,
  TError = ForbiddenResponse
>(
  params?: ListWishlistsForCurrentUserParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listWishlistsForCurrentUser>>,
        TError,
        TData
      >
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getListWishlistsForCurrentUserSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Creates a new wishlist for the current user in the current store.
 * @summary Create a Wishlist
 */
export const createWishlist = (
  createWishlistBody: BodyType<CreateWishlistBody>,
  params?: CreateWishlistParams
) => {
  return customInstance<WishlistResponse>({
    url: `/api/v2/storefront/wishlists`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createWishlistBody,
    params
  });
};

export const getCreateWishlistMutationOptions = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createWishlist>>,
    TError,
    { data: BodyType<CreateWishlistBody>; params?: CreateWishlistParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createWishlist>>,
  TError,
  { data: BodyType<CreateWishlistBody>; params?: CreateWishlistParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createWishlist>>,
    { data: BodyType<CreateWishlistBody>; params?: CreateWishlistParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return createWishlist(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateWishlistMutationResult = NonNullable<Awaited<ReturnType<typeof createWishlist>>>;
export type CreateWishlistMutationBody = BodyType<CreateWishlistBody>;
export type CreateWishlistMutationError = ForbiddenResponse | UnprocessableEntityResponse;

/**
 * @summary Create a Wishlist
 */
export const useCreateWishlist = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createWishlist>>,
    TError,
    { data: BodyType<CreateWishlistBody>; params?: CreateWishlistParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof createWishlist>>,
  TError,
  { data: BodyType<CreateWishlistBody>; params?: CreateWishlistParams },
  TContext
> => {
  const mutationOptions = getCreateWishlistMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Retrieves a wishlist using the wishlist token.

If the wishlist is publicly viewable, the endpoint will return the requested wishlist regardless of the user. If the wishlist is private, only the wishlist owner can access the wishlist.
 * @summary Retrieve a Wishlist
 */
export const getWishlistDetails = (
  token: string,
  params?: GetWishlistDetailsParams,
  signal?: AbortSignal
) => {
  return customInstance<WishlistResponse>({
    url: `/api/v2/storefront/wishlists/${token}`,
    method: 'GET',
    params,
    signal
  });
};

export const getGetWishlistDetailsQueryKey = (token: string, params?: GetWishlistDetailsParams) => {
  return [`/api/v2/storefront/wishlists/${token}`, ...(params ? [params] : [])] as const;
};

export const getGetWishlistDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof getWishlistDetails>>,
  TError = ForbiddenResponse
>(
  token: string,
  params?: GetWishlistDetailsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWishlistDetails>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWishlistDetailsQueryKey(token, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWishlistDetails>>> = ({ signal }) =>
    getWishlistDetails(token, params, signal);

  return { queryKey, queryFn, enabled: !!token, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWishlistDetails>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWishlistDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWishlistDetails>>
>;
export type GetWishlistDetailsQueryError = ForbiddenResponse;

/**
 * @summary Retrieve a Wishlist
 */
export const useGetWishlistDetails = <
  TData = Awaited<ReturnType<typeof getWishlistDetails>>,
  TError = ForbiddenResponse
>(
  token: string,
  params?: GetWishlistDetailsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWishlistDetails>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetWishlistDetailsQueryOptions(token, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetWishlistDetailsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getWishlistDetails>>,
  TError = ForbiddenResponse
>(
  token: string,
  params?: GetWishlistDetailsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getWishlistDetails>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWishlistDetailsQueryKey(token, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWishlistDetails>>> = ({ signal }) =>
    getWishlistDetails(token, params, signal);

  return { queryKey, queryFn, enabled: !!token, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getWishlistDetails>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWishlistDetailsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWishlistDetails>>
>;
export type GetWishlistDetailsSuspenseQueryError = ForbiddenResponse;

/**
 * @summary Retrieve a Wishlist
 */
export const useGetWishlistDetailsSuspense = <
  TData = Awaited<ReturnType<typeof getWishlistDetails>>,
  TError = ForbiddenResponse
>(
  token: string,
  params?: GetWishlistDetailsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getWishlistDetails>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetWishlistDetailsSuspenseQueryOptions(token, params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Updates the specific Wishlist by setting the values passed in the request body. Any parameters not provided will be left unchanged.
 * @summary Update a Wishlist
 */
export const updateWishlist = (
  token: string,
  updateWishlistBody: BodyType<UpdateWishlistBody>,
  params?: UpdateWishlistParams
) => {
  return customInstance<WishlistResponse>({
    url: `/api/v2/storefront/wishlists/${token}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: updateWishlistBody,
    params
  });
};

export const getUpdateWishlistMutationOptions = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateWishlist>>,
    TError,
    { token: string; data: BodyType<UpdateWishlistBody>; params?: UpdateWishlistParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateWishlist>>,
  TError,
  { token: string; data: BodyType<UpdateWishlistBody>; params?: UpdateWishlistParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateWishlist>>,
    { token: string; data: BodyType<UpdateWishlistBody>; params?: UpdateWishlistParams }
  > = (props) => {
    const { token, data, params } = props ?? {};

    return updateWishlist(token, data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateWishlistMutationResult = NonNullable<Awaited<ReturnType<typeof updateWishlist>>>;
export type UpdateWishlistMutationBody = BodyType<UpdateWishlistBody>;
export type UpdateWishlistMutationError = ForbiddenResponse | UnprocessableEntityResponse;

/**
 * @summary Update a Wishlist
 */
export const useUpdateWishlist = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateWishlist>>,
    TError,
    { token: string; data: BodyType<UpdateWishlistBody>; params?: UpdateWishlistParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateWishlist>>,
  TError,
  { token: string; data: BodyType<UpdateWishlistBody>; params?: UpdateWishlistParams },
  TContext
> => {
  const mutationOptions = getUpdateWishlistMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * This operation deletes the wishlist identified in the URI `token`.
 * @summary Delete a Wishlist
 */
export const deleteWishlist = (token: string) => {
  return customInstance<void>({ url: `/api/v2/storefront/wishlists/${token}`, method: 'DELETE' });
};

export const getDeleteWishlistMutationOptions = <
  TError = ForbiddenResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteWishlist>>,
    TError,
    { token: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteWishlist>>,
  TError,
  { token: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteWishlist>>,
    { token: string }
  > = (props) => {
    const { token } = props ?? {};

    return deleteWishlist(token);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteWishlistMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWishlist>>>;

export type DeleteWishlistMutationError = ForbiddenResponse;

/**
 * @summary Delete a Wishlist
 */
export const useDeleteWishlist = <TError = ForbiddenResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteWishlist>>,
    TError,
    { token: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteWishlist>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationOptions = getDeleteWishlistMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Returns the default wishlist for the current user, in the current store. If the user does not have a default wishlist in the current store one will be created.
 * @summary Retrieve the default Wishlist
 */
export const getDefaultWishlist = (params?: GetDefaultWishlistParams, signal?: AbortSignal) => {
  return customInstance<WishlistResponse>({
    url: `/api/v2/storefront/wishlists/default`,
    method: 'GET',
    params,
    signal
  });
};

export const getGetDefaultWishlistQueryKey = (params?: GetDefaultWishlistParams) => {
  return [`/api/v2/storefront/wishlists/default`, ...(params ? [params] : [])] as const;
};

export const getGetDefaultWishlistQueryOptions = <
  TData = Awaited<ReturnType<typeof getDefaultWishlist>>,
  TError = ForbiddenResponse
>(
  params?: GetDefaultWishlistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultWishlist>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDefaultWishlistQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDefaultWishlist>>> = ({ signal }) =>
    getDefaultWishlist(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDefaultWishlist>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDefaultWishlistQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDefaultWishlist>>
>;
export type GetDefaultWishlistQueryError = ForbiddenResponse;

/**
 * @summary Retrieve the default Wishlist
 */
export const useGetDefaultWishlist = <
  TData = Awaited<ReturnType<typeof getDefaultWishlist>>,
  TError = ForbiddenResponse
>(
  params?: GetDefaultWishlistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultWishlist>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetDefaultWishlistQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetDefaultWishlistSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getDefaultWishlist>>,
  TError = ForbiddenResponse
>(
  params?: GetDefaultWishlistParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDefaultWishlist>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDefaultWishlistQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDefaultWishlist>>> = ({ signal }) =>
    getDefaultWishlist(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getDefaultWishlist>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDefaultWishlistSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDefaultWishlist>>
>;
export type GetDefaultWishlistSuspenseQueryError = ForbiddenResponse;

/**
 * @summary Retrieve the default Wishlist
 */
export const useGetDefaultWishlistSuspense = <
  TData = Awaited<ReturnType<typeof getDefaultWishlist>>,
  TError = ForbiddenResponse
>(
  params?: GetDefaultWishlistParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDefaultWishlist>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetDefaultWishlistSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
