/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  GetMenuParams,
  GetMenusParams,
  MenuListResponse,
  MenuResponse,
  NotFoundResponse
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';

/**
 * Returns a list of all menus available in the current store.
 * @summary List all Menus
 */
export const getMenus = (params?: GetMenusParams, signal?: AbortSignal) => {
  return customInstance<MenuListResponse>({
    url: `/api/v2/storefront/menus`,
    method: 'GET',
    params,
    signal
  });
};

export const getGetMenusQueryKey = (params?: GetMenusParams) => {
  return [`/api/v2/storefront/menus`, ...(params ? [params] : [])] as const;
};

export const getGetMenusQueryOptions = <
  TData = Awaited<ReturnType<typeof getMenus>>,
  TError = NotFoundResponse
>(
  params?: GetMenusParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenus>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMenusQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMenus>>> = ({ signal }) =>
    getMenus(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMenus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMenusQueryResult = NonNullable<Awaited<ReturnType<typeof getMenus>>>;
export type GetMenusQueryError = NotFoundResponse;

/**
 * @summary List all Menus
 */
export const useGetMenus = <
  TData = Awaited<ReturnType<typeof getMenus>>,
  TError = NotFoundResponse
>(
  params?: GetMenusParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenus>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMenusQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetMenusSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMenus>>,
  TError = NotFoundResponse
>(
  params?: GetMenusParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMenus>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMenusQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMenus>>> = ({ signal }) =>
    getMenus(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMenus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMenusSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMenus>>>;
export type GetMenusSuspenseQueryError = NotFoundResponse;

/**
 * @summary List all Menus
 */
export const useGetMenusSuspense = <
  TData = Awaited<ReturnType<typeof getMenus>>,
  TError = NotFoundResponse
>(
  params?: GetMenusParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMenus>>, TError, TData>>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMenusSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Returns the dertails of a specified menu.
 * @summary Retrieve a  Menu
 */
export const getMenu = (id: string, params?: GetMenuParams, signal?: AbortSignal) => {
  return customInstance<MenuResponse>({
    url: `/api/v2/storefront/menus/${id}`,
    method: 'GET',
    params,
    signal
  });
};

export const getGetMenuQueryKey = (id: string, params?: GetMenuParams) => {
  return [`/api/v2/storefront/menus/${id}`, ...(params ? [params] : [])] as const;
};

export const getGetMenuQueryOptions = <
  TData = Awaited<ReturnType<typeof getMenu>>,
  TError = NotFoundResponse
>(
  id: string,
  params?: GetMenuParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMenuQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMenu>>> = ({ signal }) =>
    getMenu(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMenu>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMenuQueryResult = NonNullable<Awaited<ReturnType<typeof getMenu>>>;
export type GetMenuQueryError = NotFoundResponse;

/**
 * @summary Retrieve a  Menu
 */
export const useGetMenu = <TData = Awaited<ReturnType<typeof getMenu>>, TError = NotFoundResponse>(
  id: string,
  params?: GetMenuParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData>> }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMenuQueryOptions(id, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetMenuSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMenu>>,
  TError = NotFoundResponse
>(
  id: string,
  params?: GetMenuParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMenuQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMenu>>> = ({ signal }) =>
    getMenu(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMenu>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMenuSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMenu>>>;
export type GetMenuSuspenseQueryError = NotFoundResponse;

/**
 * @summary Retrieve a  Menu
 */
export const useGetMenuSuspense = <
  TData = Awaited<ReturnType<typeof getMenu>>,
  TError = NotFoundResponse
>(
  id: string,
  params?: GetMenuParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData>>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMenuSuspenseQueryOptions(id, params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
