/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type { ForbiddenResponse, ShowCurrentStoreParams, StoreResponse } from '.././schema';
import { customInstance } from '../../../config/custom-instance';

/**
 * Returns the current Store. [Read more about Stores](/developer/core-concepts/stores)
 * @summary Return the current Store
 */
export const showCurrentStore = (params?: ShowCurrentStoreParams, signal?: AbortSignal) => {
  return customInstance<StoreResponse>({
    url: `/api/v2/storefront/store`,
    method: 'GET',
    params,
    signal
  });
};

export const getShowCurrentStoreQueryKey = (params?: ShowCurrentStoreParams) => {
  return [`/api/v2/storefront/store`, ...(params ? [params] : [])] as const;
};

export const getShowCurrentStoreQueryOptions = <
  TData = Awaited<ReturnType<typeof showCurrentStore>>,
  TError = ForbiddenResponse
>(
  params?: ShowCurrentStoreParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof showCurrentStore>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShowCurrentStoreQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showCurrentStore>>> = ({ signal }) =>
    showCurrentStore(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof showCurrentStore>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShowCurrentStoreQueryResult = NonNullable<Awaited<ReturnType<typeof showCurrentStore>>>;
export type ShowCurrentStoreQueryError = ForbiddenResponse;

/**
 * @summary Return the current Store
 */
export const useShowCurrentStore = <
  TData = Awaited<ReturnType<typeof showCurrentStore>>,
  TError = ForbiddenResponse
>(
  params?: ShowCurrentStoreParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof showCurrentStore>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShowCurrentStoreQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getShowCurrentStoreSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof showCurrentStore>>,
  TError = ForbiddenResponse
>(
  params?: ShowCurrentStoreParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof showCurrentStore>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShowCurrentStoreQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showCurrentStore>>> = ({ signal }) =>
    showCurrentStore(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof showCurrentStore>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShowCurrentStoreSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof showCurrentStore>>
>;
export type ShowCurrentStoreSuspenseQueryError = ForbiddenResponse;

/**
 * @summary Return the current Store
 */
export const useShowCurrentStoreSuspense = <
  TData = Awaited<ReturnType<typeof showCurrentStore>>,
  TError = ForbiddenResponse
>(
  params?: ShowCurrentStoreParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof showCurrentStore>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShowCurrentStoreSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
