/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  CartResponse,
  CreatePaymentBody,
  CreatePaymentParams,
  NotFoundResponse,
  PaymentMethodListResponse,
  UnprocessableEntityResponse
} from '.././schema';
import { customInstance } from '../../config/custom-instance';
import type { BodyType } from '../../config/custom-instance';

/**
 * Creates new Payment for the current checkout.

You can either create new payment source (eg. a Credit Card) or use an existing (for signed in users only).

Newly created payment source will be associated to the current signed in user.

System will automatically invalidate previous (non-finalized) payments (excluding store credit / gift card payments).

[More details on payment system](/developer/core-concepts/payments)
 * @summary Create new Payment
 */
export const createPayment = (
  createPaymentBody: BodyType<CreatePaymentBody>,
  params?: CreatePaymentParams
) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/checkout/create_payment`,
    method: 'POST',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: createPaymentBody,
    params
  });
};

export const getCreatePaymentMutationOptions = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPayment>>,
    TError,
    { data: BodyType<CreatePaymentBody>; params?: CreatePaymentParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPayment>>,
  TError,
  { data: BodyType<CreatePaymentBody>; params?: CreatePaymentParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPayment>>,
    { data: BodyType<CreatePaymentBody>; params?: CreatePaymentParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return createPayment(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof createPayment>>>;
export type CreatePaymentMutationBody = BodyType<CreatePaymentBody>;
export type CreatePaymentMutationError = NotFoundResponse | UnprocessableEntityResponse;

/**
 * @summary Create new Payment
 */
export const useCreatePayment = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPayment>>,
    TError,
    { data: BodyType<CreatePaymentBody>; params?: CreatePaymentParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof createPayment>>,
  TError,
  { data: BodyType<CreatePaymentBody>; params?: CreatePaymentParams },
  TContext
> => {
  const mutationOptions = getCreatePaymentMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Returns a list of available payment methods for this checkout.
 * @summary List Payment Methods
 */
export const paymentMethods = (signal?: AbortSignal) => {
  return customInstance<PaymentMethodListResponse>({
    url: `/api/v2/storefront/checkout/payment_methods`,
    method: 'GET',
    signal
  });
};

export const getPaymentMethodsQueryKey = () => {
  return [`/api/v2/storefront/checkout/payment_methods`] as const;
};

export const getPaymentMethodsQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentMethods>>,
  TError = NotFoundResponse
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentMethods>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPaymentMethodsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentMethods>>> = ({ signal }) =>
    paymentMethods(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof paymentMethods>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PaymentMethodsQueryResult = NonNullable<Awaited<ReturnType<typeof paymentMethods>>>;
export type PaymentMethodsQueryError = NotFoundResponse;

/**
 * @summary List Payment Methods
 */
export const usePaymentMethods = <
  TData = Awaited<ReturnType<typeof paymentMethods>>,
  TError = NotFoundResponse
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentMethods>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getPaymentMethodsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getPaymentMethodsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentMethods>>,
  TError = NotFoundResponse
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof paymentMethods>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPaymentMethodsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentMethods>>> = ({ signal }) =>
    paymentMethods(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof paymentMethods>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PaymentMethodsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof paymentMethods>>
>;
export type PaymentMethodsSuspenseQueryError = NotFoundResponse;

/**
 * @summary List Payment Methods
 */
export const usePaymentMethodsSuspense = <
  TData = Awaited<ReturnType<typeof paymentMethods>>,
  TError = NotFoundResponse
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof paymentMethods>>, TError, TData>
  >;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getPaymentMethodsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
