/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  CartListResponse,
  CartResponse,
  CompletedOrdersParams,
  CompletedUserOrderParams,
  ForbiddenResponse
} from '.././schema';
import { customInstance } from '../../config/custom-instance';

/**
 * Returns all completed orders placed by the current user in the current store.
 * @summary List all Orders
 */
export const completedOrders = (params?: CompletedOrdersParams, signal?: AbortSignal) => {
  return customInstance<CartListResponse>({
    url: `/api/v2/storefront/account/orders`,
    method: 'GET',
    params,
    signal
  });
};

export const getCompletedOrdersQueryKey = (params?: CompletedOrdersParams) => {
  return [`/api/v2/storefront/account/orders`, ...(params ? [params] : [])] as const;
};

export const getCompletedOrdersQueryOptions = <
  TData = Awaited<ReturnType<typeof completedOrders>>,
  TError = ForbiddenResponse
>(
  params?: CompletedOrdersParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof completedOrders>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompletedOrdersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof completedOrders>>> = ({ signal }) =>
    completedOrders(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof completedOrders>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CompletedOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof completedOrders>>>;
export type CompletedOrdersQueryError = ForbiddenResponse;

/**
 * @summary List all Orders
 */
export const useCompletedOrders = <
  TData = Awaited<ReturnType<typeof completedOrders>>,
  TError = ForbiddenResponse
>(
  params?: CompletedOrdersParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof completedOrders>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCompletedOrdersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getCompletedOrdersSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof completedOrders>>,
  TError = ForbiddenResponse
>(
  params?: CompletedOrdersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof completedOrders>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompletedOrdersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof completedOrders>>> = ({ signal }) =>
    completedOrders(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof completedOrders>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CompletedOrdersSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof completedOrders>>
>;
export type CompletedOrdersSuspenseQueryError = ForbiddenResponse;

/**
 * @summary List all Orders
 */
export const useCompletedOrdersSuspense = <
  TData = Awaited<ReturnType<typeof completedOrders>>,
  TError = ForbiddenResponse
>(
  params?: CompletedOrdersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof completedOrders>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCompletedOrdersSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Returns a completed order for the current user within the scope of the current store.
 * @summary Retrieve an Order
 */
export const completedUserOrder = (
  orderNumber: string,
  params?: CompletedUserOrderParams,
  signal?: AbortSignal
) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/account/orders/${orderNumber}`,
    method: 'GET',
    params,
    signal
  });
};

export const getCompletedUserOrderQueryKey = (
  orderNumber: string,
  params?: CompletedUserOrderParams
) => {
  return [`/api/v2/storefront/account/orders/${orderNumber}`, ...(params ? [params] : [])] as const;
};

export const getCompletedUserOrderQueryOptions = <
  TData = Awaited<ReturnType<typeof completedUserOrder>>,
  TError = ForbiddenResponse
>(
  orderNumber: string,
  params?: CompletedUserOrderParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof completedUserOrder>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompletedUserOrderQueryKey(orderNumber, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof completedUserOrder>>> = ({ signal }) =>
    completedUserOrder(orderNumber, params, signal);

  return { queryKey, queryFn, enabled: !!orderNumber, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof completedUserOrder>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CompletedUserOrderQueryResult = NonNullable<
  Awaited<ReturnType<typeof completedUserOrder>>
>;
export type CompletedUserOrderQueryError = ForbiddenResponse;

/**
 * @summary Retrieve an Order
 */
export const useCompletedUserOrder = <
  TData = Awaited<ReturnType<typeof completedUserOrder>>,
  TError = ForbiddenResponse
>(
  orderNumber: string,
  params?: CompletedUserOrderParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof completedUserOrder>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCompletedUserOrderQueryOptions(orderNumber, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getCompletedUserOrderSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof completedUserOrder>>,
  TError = ForbiddenResponse
>(
  orderNumber: string,
  params?: CompletedUserOrderParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof completedUserOrder>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompletedUserOrderQueryKey(orderNumber, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof completedUserOrder>>> = ({ signal }) =>
    completedUserOrder(orderNumber, params, signal);

  return { queryKey, queryFn, enabled: !!orderNumber, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof completedUserOrder>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CompletedUserOrderSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof completedUserOrder>>
>;
export type CompletedUserOrderSuspenseQueryError = ForbiddenResponse;

/**
 * @summary Retrieve an Order
 */
export const useCompletedUserOrderSuspense = <
  TData = Awaited<ReturnType<typeof completedUserOrder>>,
  TError = ForbiddenResponse
>(
  orderNumber: string,
  params?: CompletedUserOrderParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof completedUserOrder>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCompletedUserOrderSuspenseQueryOptions(orderNumber, params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
