/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';
import type {
  AddStoreCreditParams,
  CartResponse,
  NotFoundResponse,
  RemoveStoreCreditParams,
  UnprocessableEntityResponse
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';

/**
 * The Add Store Credit endpoint takes the users existing store credit from their account and adds a set amount of this store credit to the current cart.

In essence, by adding the user's store credit to a cart, the user's store credit is being spent.
 * @summary Add Store Credit
 */
export const addStoreCredit = (params?: AddStoreCreditParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/checkout/add_store_credit`,
    method: 'POST',
    params
  });
};

export const getAddStoreCreditMutationOptions = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addStoreCredit>>,
    TError,
    { params?: AddStoreCreditParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addStoreCredit>>,
  TError,
  { params?: AddStoreCreditParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addStoreCredit>>,
    { params?: AddStoreCreditParams }
  > = (props) => {
    const { params } = props ?? {};

    return addStoreCredit(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddStoreCreditMutationResult = NonNullable<Awaited<ReturnType<typeof addStoreCredit>>>;

export type AddStoreCreditMutationError = NotFoundResponse | UnprocessableEntityResponse;

/**
 * @summary Add Store Credit
 */
export const useAddStoreCredit = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addStoreCredit>>,
    TError,
    { params?: AddStoreCreditParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof addStoreCredit>>,
  TError,
  { params?: AddStoreCreditParams },
  TContext
> => {
  const mutationOptions = getAddStoreCreditMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Removes store credit from the cart if any had previously been applied.
 * @summary Remove Store Credit
 */
export const removeStoreCredit = (params?: RemoveStoreCreditParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/checkout/remove_store_credit`,
    method: 'POST',
    params
  });
};

export const getRemoveStoreCreditMutationOptions = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeStoreCredit>>,
    TError,
    { params?: RemoveStoreCreditParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeStoreCredit>>,
  TError,
  { params?: RemoveStoreCreditParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeStoreCredit>>,
    { params?: RemoveStoreCreditParams }
  > = (props) => {
    const { params } = props ?? {};

    return removeStoreCredit(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveStoreCreditMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeStoreCredit>>
>;

export type RemoveStoreCreditMutationError = NotFoundResponse | UnprocessableEntityResponse;

/**
 * @summary Remove Store Credit
 */
export const useRemoveStoreCredit = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeStoreCredit>>,
    TError,
    { params?: RemoveStoreCreditParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeStoreCredit>>,
  TError,
  { params?: RemoveStoreCreditParams },
  TContext
> => {
  const mutationOptions = getRemoveStoreCreditMutationOptions(options);

  return useMutation(mutationOptions);
};
