/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  CountryListResponse,
  CountryResponse,
  DefaultCountryParams,
  NotFoundResponse,
  ShowCountryParams
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';

/**
 * Returns a list of all countries.
 * @summary List all Countries
 */
export const countriesList = (signal?: AbortSignal) => {
  return customInstance<CountryListResponse>({
    url: `/api/v2/storefront/countries`,
    method: 'GET',
    signal
  });
};

export const getCountriesListQueryKey = () => {
  return [`/api/v2/storefront/countries`] as const;
};

export const getCountriesListQueryOptions = <
  TData = Awaited<ReturnType<typeof countriesList>>,
  TError = unknown
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof countriesList>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCountriesListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof countriesList>>> = ({ signal }) =>
    countriesList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof countriesList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CountriesListQueryResult = NonNullable<Awaited<ReturnType<typeof countriesList>>>;
export type CountriesListQueryError = unknown;

/**
 * @summary List all Countries
 */
export const useCountriesList = <
  TData = Awaited<ReturnType<typeof countriesList>>,
  TError = unknown
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof countriesList>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCountriesListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getCountriesListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof countriesList>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof countriesList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCountriesListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof countriesList>>> = ({ signal }) =>
    countriesList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof countriesList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CountriesListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof countriesList>>
>;
export type CountriesListSuspenseQueryError = unknown;

/**
 * @summary List all Countries
 */
export const useCountriesListSuspense = <
  TData = Awaited<ReturnType<typeof countriesList>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof countriesList>>, TError, TData>
  >;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCountriesListSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Returns the details of a specific country.
 * @summary Retrieve a Country
 */
export const showCountry = (iso: string, params?: ShowCountryParams, signal?: AbortSignal) => {
  return customInstance<CountryResponse>({
    url: `/api/v2/storefront/countries/${iso}`,
    method: 'GET',
    params,
    signal
  });
};

export const getShowCountryQueryKey = (iso: string, params?: ShowCountryParams) => {
  return [`/api/v2/storefront/countries/${iso}`, ...(params ? [params] : [])] as const;
};

export const getShowCountryQueryOptions = <
  TData = Awaited<ReturnType<typeof showCountry>>,
  TError = NotFoundResponse
>(
  iso: string,
  params?: ShowCountryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof showCountry>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShowCountryQueryKey(iso, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showCountry>>> = ({ signal }) =>
    showCountry(iso, params, signal);

  return { queryKey, queryFn, enabled: !!iso, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof showCountry>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShowCountryQueryResult = NonNullable<Awaited<ReturnType<typeof showCountry>>>;
export type ShowCountryQueryError = NotFoundResponse;

/**
 * @summary Retrieve a Country
 */
export const useShowCountry = <
  TData = Awaited<ReturnType<typeof showCountry>>,
  TError = NotFoundResponse
>(
  iso: string,
  params?: ShowCountryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof showCountry>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShowCountryQueryOptions(iso, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getShowCountrySuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof showCountry>>,
  TError = NotFoundResponse
>(
  iso: string,
  params?: ShowCountryParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof showCountry>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShowCountryQueryKey(iso, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showCountry>>> = ({ signal }) =>
    showCountry(iso, params, signal);

  return { queryKey, queryFn, enabled: !!iso, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof showCountry>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShowCountrySuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof showCountry>>>;
export type ShowCountrySuspenseQueryError = NotFoundResponse;

/**
 * @summary Retrieve a Country
 */
export const useShowCountrySuspense = <
  TData = Awaited<ReturnType<typeof showCountry>>,
  TError = NotFoundResponse
>(
  iso: string,
  params?: ShowCountryParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof showCountry>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShowCountrySuspenseQueryOptions(iso, params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Returns the default country for the current store. By default this will be the US.
 * @summary Get Default Country
 */
export const defaultCountry = (params?: DefaultCountryParams, signal?: AbortSignal) => {
  return customInstance<CountryResponse>({
    url: `/api/v2/storefront/countries/default`,
    method: 'GET',
    params,
    signal
  });
};

export const getDefaultCountryQueryKey = (params?: DefaultCountryParams) => {
  return [`/api/v2/storefront/countries/default`, ...(params ? [params] : [])] as const;
};

export const getDefaultCountryQueryOptions = <
  TData = Awaited<ReturnType<typeof defaultCountry>>,
  TError = unknown
>(
  params?: DefaultCountryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof defaultCountry>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDefaultCountryQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof defaultCountry>>> = ({ signal }) =>
    defaultCountry(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof defaultCountry>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DefaultCountryQueryResult = NonNullable<Awaited<ReturnType<typeof defaultCountry>>>;
export type DefaultCountryQueryError = unknown;

/**
 * @summary Get Default Country
 */
export const useDefaultCountry = <
  TData = Awaited<ReturnType<typeof defaultCountry>>,
  TError = unknown
>(
  params?: DefaultCountryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof defaultCountry>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDefaultCountryQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getDefaultCountrySuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof defaultCountry>>,
  TError = unknown
>(
  params?: DefaultCountryParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof defaultCountry>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDefaultCountryQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof defaultCountry>>> = ({ signal }) =>
    defaultCountry(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof defaultCountry>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DefaultCountrySuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof defaultCountry>>
>;
export type DefaultCountrySuspenseQueryError = unknown;

/**
 * @summary Get Default Country
 */
export const useDefaultCountrySuspense = <
  TData = Awaited<ReturnType<typeof defaultCountry>>,
  TError = unknown
>(
  params?: DefaultCountryParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof defaultCountry>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDefaultCountrySuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
