/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';
import type {
  ApplyCouponCodeBody,
  ApplyCouponCodeParams,
  CartResponse,
  RemoveAllCouponCodesParams,
  RemoveCouponCodeParams,
  UnprocessableEntityResponse
} from '.././schema';
import { customInstance } from '../../config/custom-instance';
import type { BodyType } from '../../config/custom-instance';

/**
 * Applies a coupon code to the current cart.
 * @summary Apply a Coupon Code
 */
export const applyCouponCode = (
  applyCouponCodeBody: BodyType<ApplyCouponCodeBody>,
  params?: ApplyCouponCodeParams
) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart/apply_coupon_code`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: applyCouponCodeBody,
    params
  });
};

export const getApplyCouponCodeMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof applyCouponCode>>,
    TError,
    { data: BodyType<ApplyCouponCodeBody>; params?: ApplyCouponCodeParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof applyCouponCode>>,
  TError,
  { data: BodyType<ApplyCouponCodeBody>; params?: ApplyCouponCodeParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof applyCouponCode>>,
    { data: BodyType<ApplyCouponCodeBody>; params?: ApplyCouponCodeParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return applyCouponCode(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApplyCouponCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof applyCouponCode>>
>;
export type ApplyCouponCodeMutationBody = BodyType<ApplyCouponCodeBody>;
export type ApplyCouponCodeMutationError = UnprocessableEntityResponse;

/**
 * @summary Apply a Coupon Code
 */
export const useApplyCouponCode = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof applyCouponCode>>,
    TError,
    { data: BodyType<ApplyCouponCodeBody>; params?: ApplyCouponCodeParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof applyCouponCode>>,
  TError,
  { data: BodyType<ApplyCouponCodeBody>; params?: ApplyCouponCodeParams },
  TContext
> => {
  const mutationOptions = getApplyCouponCodeMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Removes a specified coupon code from the current cart.
 * @summary Remove a Coupon
 */
export const removeCouponCode = (couponCode: string, params?: RemoveCouponCodeParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart/remove_coupon_code/${couponCode}`,
    method: 'DELETE',
    params
  });
};

export const getRemoveCouponCodeMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeCouponCode>>,
    TError,
    { couponCode: string; params?: RemoveCouponCodeParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeCouponCode>>,
  TError,
  { couponCode: string; params?: RemoveCouponCodeParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeCouponCode>>,
    { couponCode: string; params?: RemoveCouponCodeParams }
  > = (props) => {
    const { couponCode, params } = props ?? {};

    return removeCouponCode(couponCode, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveCouponCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeCouponCode>>
>;

export type RemoveCouponCodeMutationError = UnprocessableEntityResponse;

/**
 * @summary Remove a Coupon
 */
export const useRemoveCouponCode = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeCouponCode>>,
    TError,
    { couponCode: string; params?: RemoveCouponCodeParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeCouponCode>>,
  TError,
  { couponCode: string; params?: RemoveCouponCodeParams },
  TContext
> => {
  const mutationOptions = getRemoveCouponCodeMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Removes all coupons that have been applied to the current cart.
 * @summary Remove all Coupons
 */
export const removeAllCouponCodes = (params?: RemoveAllCouponCodesParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart/remove_coupon_code`,
    method: 'DELETE',
    params
  });
};

export const getRemoveAllCouponCodesMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeAllCouponCodes>>,
    TError,
    { params?: RemoveAllCouponCodesParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeAllCouponCodes>>,
  TError,
  { params?: RemoveAllCouponCodesParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeAllCouponCodes>>,
    { params?: RemoveAllCouponCodesParams }
  > = (props) => {
    const { params } = props ?? {};

    return removeAllCouponCodes(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveAllCouponCodesMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeAllCouponCodes>>
>;

export type RemoveAllCouponCodesMutationError = UnprocessableEntityResponse;

/**
 * @summary Remove all Coupons
 */
export const useRemoveAllCouponCodes = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeAllCouponCodes>>,
    TError,
    { params?: RemoveAllCouponCodesParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeAllCouponCodes>>,
  TError,
  { params?: RemoveAllCouponCodesParams },
  TContext
> => {
  const mutationOptions = getRemoveAllCouponCodesMutationOptions(options);

  return useMutation(mutationOptions);
};
