/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type { CartResponse, NotFoundResponse, OrderStatusParams } from '.././schema';
import { customInstance } from '../../config/custom-instance';

/**
 * Returns completed order information.

This endpoint is useful when fetching orders placed by a guest user, allowing customers without an account to check the status of their order: (shipment/payment/processing) etc.

Pass the cart `token` value as the `X-Spree-Order-Token` for authorization, and the corresponding cart `number` in the URI **{order_number}** to successfully retrieve an order.
 * @summary Retrieve an Order Status
 */
export const orderStatus = (
  orderNumber: string,
  params?: OrderStatusParams,
  signal?: AbortSignal
) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/order_status/${orderNumber}`,
    method: 'GET',
    params,
    signal
  });
};

export const getOrderStatusQueryKey = (orderNumber: string, params?: OrderStatusParams) => {
  return [`/api/v2/storefront/order_status/${orderNumber}`, ...(params ? [params] : [])] as const;
};

export const getOrderStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof orderStatus>>,
  TError = NotFoundResponse
>(
  orderNumber: string,
  params?: OrderStatusParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof orderStatus>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrderStatusQueryKey(orderNumber, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof orderStatus>>> = ({ signal }) =>
    orderStatus(orderNumber, params, signal);

  return { queryKey, queryFn, enabled: !!orderNumber, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof orderStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type OrderStatusQueryResult = NonNullable<Awaited<ReturnType<typeof orderStatus>>>;
export type OrderStatusQueryError = NotFoundResponse;

/**
 * @summary Retrieve an Order Status
 */
export const useOrderStatus = <
  TData = Awaited<ReturnType<typeof orderStatus>>,
  TError = NotFoundResponse
>(
  orderNumber: string,
  params?: OrderStatusParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof orderStatus>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getOrderStatusQueryOptions(orderNumber, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getOrderStatusSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof orderStatus>>,
  TError = NotFoundResponse
>(
  orderNumber: string,
  params?: OrderStatusParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof orderStatus>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrderStatusQueryKey(orderNumber, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof orderStatus>>> = ({ signal }) =>
    orderStatus(orderNumber, params, signal);

  return { queryKey, queryFn, enabled: !!orderNumber, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof orderStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type OrderStatusSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof orderStatus>>>;
export type OrderStatusSuspenseQueryError = NotFoundResponse;

/**
 * @summary Retrieve an Order Status
 */
export const useOrderStatusSuspense = <
  TData = Awaited<ReturnType<typeof orderStatus>>,
  TError = NotFoundResponse
>(
  orderNumber: string,
  params?: OrderStatusParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof orderStatus>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getOrderStatusSuspenseQueryOptions(orderNumber, params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
