/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';
import type {
  AddItemBody,
  AddItemParams,
  CartResponse,
  NotFoundResponse,
  RemoveLineItemParams,
  SetQuantityBody,
  SetQuantityParams,
  UnprocessableEntityResponse
} from '.././schema';
import { customInstance } from '../../config/custom-instance';
import type { BodyType } from '../../config/custom-instance';

/**
 * Adds a variant to the current cart by creating a line item. Each line item represents a specified variant and the desired quantity.
 * @summary Add an Item to Cart
 */
export const addItem = (addItemBody: BodyType<AddItemBody>, params?: AddItemParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart/add_item`,
    method: 'POST',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: addItemBody,
    params
  });
};

export const getAddItemMutationOptions = <TError = NotFoundResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addItem>>,
    TError,
    { data: BodyType<AddItemBody>; params?: AddItemParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addItem>>,
  TError,
  { data: BodyType<AddItemBody>; params?: AddItemParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addItem>>,
    { data: BodyType<AddItemBody>; params?: AddItemParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return addItem(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddItemMutationResult = NonNullable<Awaited<ReturnType<typeof addItem>>>;
export type AddItemMutationBody = BodyType<AddItemBody>;
export type AddItemMutationError = NotFoundResponse;

/**
 * @summary Add an Item to Cart
 */
export const useAddItem = <TError = NotFoundResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addItem>>,
    TError,
    { data: BodyType<AddItemBody>; params?: AddItemParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof addItem>>,
  TError,
  { data: BodyType<AddItemBody>; params?: AddItemParams },
  TContext
> => {
  const mutationOptions = getAddItemMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Sets the quantity of a specified line item.
 * @summary Set Line Item Quantity
 */
export const setQuantity = (
  setQuantityBody: BodyType<SetQuantityBody>,
  params?: SetQuantityParams
) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart/set_quantity`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: setQuantityBody,
    params
  });
};

export const getSetQuantityMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setQuantity>>,
    TError,
    { data: BodyType<SetQuantityBody>; params?: SetQuantityParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setQuantity>>,
  TError,
  { data: BodyType<SetQuantityBody>; params?: SetQuantityParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setQuantity>>,
    { data: BodyType<SetQuantityBody>; params?: SetQuantityParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return setQuantity(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetQuantityMutationResult = NonNullable<Awaited<ReturnType<typeof setQuantity>>>;
export type SetQuantityMutationBody = BodyType<SetQuantityBody>;
export type SetQuantityMutationError = UnprocessableEntityResponse;

/**
 * @summary Set Line Item Quantity
 */
export const useSetQuantity = <TError = UnprocessableEntityResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setQuantity>>,
    TError,
    { data: BodyType<SetQuantityBody>; params?: SetQuantityParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof setQuantity>>,
  TError,
  { data: BodyType<SetQuantityBody>; params?: SetQuantityParams },
  TContext
> => {
  const mutationOptions = getSetQuantityMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Removes a line item from the cart by deleting the line item.

After deleting the line item, the system will re-calculate taxes, promotions, shipments etc.
 * @summary Remove a Line Item
 */
export const removeLineItem = (id: string, params?: RemoveLineItemParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart/remove_line_item/${id}`,
    method: 'DELETE',
    params
  });
};

export const getRemoveLineItemMutationOptions = <
  TError = NotFoundResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeLineItem>>,
    TError,
    { id: string; params?: RemoveLineItemParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeLineItem>>,
  TError,
  { id: string; params?: RemoveLineItemParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeLineItem>>,
    { id: string; params?: RemoveLineItemParams }
  > = (props) => {
    const { id, params } = props ?? {};

    return removeLineItem(id, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveLineItemMutationResult = NonNullable<Awaited<ReturnType<typeof removeLineItem>>>;

export type RemoveLineItemMutationError = NotFoundResponse;

/**
 * @summary Remove a Line Item
 */
export const useRemoveLineItem = <TError = NotFoundResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeLineItem>>,
    TError,
    { id: string; params?: RemoveLineItemParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeLineItem>>,
  TError,
  { id: string; params?: RemoveLineItemParams },
  TContext
> => {
  const mutationOptions = getRemoveLineItemMutationOptions(options);

  return useMutation(mutationOptions);
};
