/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  CreditCardListResponse,
  CreditCardResponse,
  CreditCardsListParams,
  DefaultCreditCardParams,
  ForbiddenResponse,
  NotFoundResponse
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';

/**
 * Returns a list of credit cards for the current user.
 * @summary List all Credit Cards
 */
export const creditCardsList = (params?: CreditCardsListParams, signal?: AbortSignal) => {
  return customInstance<CreditCardListResponse>({
    url: `/api/v2/storefront/account/credit_cards`,
    method: 'GET',
    params,
    signal
  });
};

export const getCreditCardsListQueryKey = (params?: CreditCardsListParams) => {
  return [`/api/v2/storefront/account/credit_cards`, ...(params ? [params] : [])] as const;
};

export const getCreditCardsListQueryOptions = <
  TData = Awaited<ReturnType<typeof creditCardsList>>,
  TError = ForbiddenResponse
>(
  params?: CreditCardsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof creditCardsList>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCreditCardsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof creditCardsList>>> = ({ signal }) =>
    creditCardsList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof creditCardsList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CreditCardsListQueryResult = NonNullable<Awaited<ReturnType<typeof creditCardsList>>>;
export type CreditCardsListQueryError = ForbiddenResponse;

/**
 * @summary List all Credit Cards
 */
export const useCreditCardsList = <
  TData = Awaited<ReturnType<typeof creditCardsList>>,
  TError = ForbiddenResponse
>(
  params?: CreditCardsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof creditCardsList>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCreditCardsListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getCreditCardsListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof creditCardsList>>,
  TError = ForbiddenResponse
>(
  params?: CreditCardsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof creditCardsList>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCreditCardsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof creditCardsList>>> = ({ signal }) =>
    creditCardsList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof creditCardsList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CreditCardsListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof creditCardsList>>
>;
export type CreditCardsListSuspenseQueryError = ForbiddenResponse;

/**
 * @summary List all Credit Cards
 */
export const useCreditCardsListSuspense = <
  TData = Awaited<ReturnType<typeof creditCardsList>>,
  TError = ForbiddenResponse
>(
  params?: CreditCardsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof creditCardsList>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCreditCardsListSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Removes a specified credit card for the current user with a soft delete to retain payment information for any pre-existing orders.
 * @summary Remove a Credit Card
 */
export const removeCreditCard = (id: string) => {
  return customInstance<void>({
    url: `/api/v2/storefront/account/credit_cards/${id}`,
    method: 'DELETE'
  });
};

export const getRemoveCreditCardMutationOptions = <
  TError = NotFoundResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeCreditCard>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeCreditCard>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeCreditCard>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return removeCreditCard(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveCreditCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeCreditCard>>
>;

export type RemoveCreditCardMutationError = NotFoundResponse;

/**
 * @summary Remove a Credit Card
 */
export const useRemoveCreditCard = <TError = NotFoundResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeCreditCard>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeCreditCard>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getRemoveCreditCardMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Returns the current user's default credit card.
 * @summary Retrieve the default Credit Card
 */
export const defaultCreditCard = (params?: DefaultCreditCardParams, signal?: AbortSignal) => {
  return customInstance<CreditCardResponse>({
    url: `/api/v2/storefront/account/credit_cards/default`,
    method: 'GET',
    params,
    signal
  });
};

export const getDefaultCreditCardQueryKey = (params?: DefaultCreditCardParams) => {
  return [`/api/v2/storefront/account/credit_cards/default`, ...(params ? [params] : [])] as const;
};

export const getDefaultCreditCardQueryOptions = <
  TData = Awaited<ReturnType<typeof defaultCreditCard>>,
  TError = ForbiddenResponse
>(
  params?: DefaultCreditCardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof defaultCreditCard>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDefaultCreditCardQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof defaultCreditCard>>> = ({ signal }) =>
    defaultCreditCard(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof defaultCreditCard>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DefaultCreditCardQueryResult = NonNullable<
  Awaited<ReturnType<typeof defaultCreditCard>>
>;
export type DefaultCreditCardQueryError = ForbiddenResponse;

/**
 * @summary Retrieve the default Credit Card
 */
export const useDefaultCreditCard = <
  TData = Awaited<ReturnType<typeof defaultCreditCard>>,
  TError = ForbiddenResponse
>(
  params?: DefaultCreditCardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof defaultCreditCard>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDefaultCreditCardQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getDefaultCreditCardSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof defaultCreditCard>>,
  TError = ForbiddenResponse
>(
  params?: DefaultCreditCardParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof defaultCreditCard>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDefaultCreditCardQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof defaultCreditCard>>> = ({ signal }) =>
    defaultCreditCard(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof defaultCreditCard>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DefaultCreditCardSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof defaultCreditCard>>
>;
export type DefaultCreditCardSuspenseQueryError = ForbiddenResponse;

/**
 * @summary Retrieve the default Credit Card
 */
export const useDefaultCreditCardSuspense = <
  TData = Awaited<ReturnType<typeof defaultCreditCard>>,
  TError = ForbiddenResponse
>(
  params?: DefaultCreditCardParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof defaultCreditCard>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDefaultCreditCardSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
