/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';
import type {
  AdvanceCheckoutParams,
  CartResponse,
  CheckoutNextParams,
  CompleteCheckoutParams,
  NotFoundResponse,
  UnprocessableEntityResponse
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';

/**
 * Goes to the next checkout step.
 * @summary Next Checkout Step
 */
export const checkoutNext = (params?: CheckoutNextParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/checkout/next`,
    method: 'PATCH',
    params
  });
};

export const getCheckoutNextMutationOptions = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof checkoutNext>>,
    TError,
    { params?: CheckoutNextParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof checkoutNext>>,
  TError,
  { params?: CheckoutNextParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof checkoutNext>>,
    { params?: CheckoutNextParams }
  > = (props) => {
    const { params } = props ?? {};

    return checkoutNext(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type CheckoutNextMutationResult = NonNullable<Awaited<ReturnType<typeof checkoutNext>>>;

export type CheckoutNextMutationError = NotFoundResponse | UnprocessableEntityResponse;

/**
 * @summary Next Checkout Step
 */
export const useCheckoutNext = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof checkoutNext>>,
    TError,
    { params?: CheckoutNextParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof checkoutNext>>,
  TError,
  { params?: CheckoutNextParams },
  TContext
> => {
  const mutationOptions = getCheckoutNextMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Advances the checkout to the furthest checkout step validation allows, up until the **completed** step.
 * @summary Advance Checkout
 */
export const advanceCheckout = (params?: AdvanceCheckoutParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/checkout/advance`,
    method: 'PATCH',
    params
  });
};

export const getAdvanceCheckoutMutationOptions = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof advanceCheckout>>,
    TError,
    { params?: AdvanceCheckoutParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof advanceCheckout>>,
  TError,
  { params?: AdvanceCheckoutParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof advanceCheckout>>,
    { params?: AdvanceCheckoutParams }
  > = (props) => {
    const { params } = props ?? {};

    return advanceCheckout(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdvanceCheckoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof advanceCheckout>>
>;

export type AdvanceCheckoutMutationError = NotFoundResponse | UnprocessableEntityResponse;

/**
 * @summary Advance Checkout
 */
export const useAdvanceCheckout = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof advanceCheckout>>,
    TError,
    { params?: AdvanceCheckoutParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof advanceCheckout>>,
  TError,
  { params?: AdvanceCheckoutParams },
  TContext
> => {
  const mutationOptions = getAdvanceCheckoutMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Completes the checkout by marking the order as complete.

**Please be aware**; Once a checkout is marked as `complete` it is considered a completed order, the Cart and Checkout endpoints will no longer access a completed order, and a new cart will need to be created.

If you want to access a completed order you will need to use the **Account / Orders** or **Order Status** endpoints.
 * @summary Complete Checkout
 */
export const completeCheckout = (params?: CompleteCheckoutParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/checkout/complete`,
    method: 'PATCH',
    params
  });
};

export const getCompleteCheckoutMutationOptions = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeCheckout>>,
    TError,
    { params?: CompleteCheckoutParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeCheckout>>,
  TError,
  { params?: CompleteCheckoutParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeCheckout>>,
    { params?: CompleteCheckoutParams }
  > = (props) => {
    const { params } = props ?? {};

    return completeCheckout(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompleteCheckoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof completeCheckout>>
>;

export type CompleteCheckoutMutationError = NotFoundResponse | UnprocessableEntityResponse;

/**
 * @summary Complete Checkout
 */
export const useCompleteCheckout = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeCheckout>>,
    TError,
    { params?: CompleteCheckoutParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof completeCheckout>>,
  TError,
  { params?: CompleteCheckoutParams },
  TContext
> => {
  const mutationOptions = getCompleteCheckoutMutationOptions(options);

  return useMutation(mutationOptions);
};
