/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { AddItemBodyOptions } from './addItemBodyOptions';
import type { AddItemBodyPrivateMetadata } from './addItemBodyPrivateMetadata';
import type { AddItemBodyPublicMetadata } from './addItemBodyPublicMetadata';

export type AddItemBody = {
  /** Additional custom options. Activate these by adding: `Spree::PermittedAttributes.line_item_attributes << :foo` in `config/initializers/spree.rb` */
  options?: AddItemBodyOptions;
  /** The private metadata for the added item. */
  private_metadata?: AddItemBodyPrivateMetadata;
  /** The public metadata for the added item. */
  public_metadata?: AddItemBodyPublicMetadata;
  quantity?: number;
  variant_id?: string;
};
