/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */

export interface AddressPayload {
  /** Street address */
  address1: string;
  /** Additional address information, floor no etc */
  address2?: string;
  /** City, town */
  city: string;
  /** Company name */
  company?: string;
  /** Country ISO (2-chars) or ISO3 (3-chars) code. [List of all codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) */
  country_iso: string;
  firstname: string;
  /** The internal name for this address (Work, Home) */
  label?: string;
  lastname: string;
  phone?: string;
  /** State/region/province 2 letter abbreviation */
  state_name?: string;
  /** Valid zipcode, will be validated against the selected Country */
  zipcode?: string;
}
