/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { Timestamp } from './timestamp';
import type { CartAttributesPaymentState } from './cartAttributesPaymentState';
import type { CartAttributesShipmentState } from './cartAttributesShipmentState';
import type { CartAttributesState } from './cartAttributesState';

export type CartAttributes = {
  additional_tax_total?: string;
  adjustment_total?: string;
  /** @nullable */
  completed_at?: string | null;
  created_at?: Timestamp;
  currency?: string;
  display_additional_tax_total?: string;
  display_adjustment_total?: string;
  display_included_tax_total?: string;
  display_item_total?: string;
  display_pre_tax_item_amount?: string;
  display_pre_tax_total?: string;
  display_promo_total?: string;
  display_ship_total?: string;
  display_tax_total?: string;
  display_total?: string;
  /** @nullable */
  email?: string | null;
  included_tax_total?: string;
  /**
   * Total quantity number of all items added to the Cart
   * @minimum 0
   */
  item_count?: number;
  item_total?: string;
  /** Used as the **{order_number}** value in the URI to identify a completed order. */
  number?: string;
  /**
   * Overall state of the Payments. Please see <a href="/developer/core-concepts/orders#order-payment-states">
  Order Payments states
</a> for a full list with description.
   * @nullable
   */
  payment_state?: CartAttributesPaymentState;
  pre_tax_item_amount?: string;
  pre_tax_total?: string;
  promo_total?: string;
  ship_total?: string;
  /**
   * Overall state of the Shipments. Please see <a href="/developer/core-concepts/orders#order-shipment-states-1">
  Order Shipments states
</a> for a full list with description.
   * @nullable
   */
  shipment_state?: CartAttributesShipmentState;
  /**
   * Message added by the Customer
   * @nullable
   */
  special_instructions?: string | null;
  /** State of the Cart in the Checkout flow. Please see <a href="/developer/core-concepts/orders#the-order-state-machine">
  The Order State machine
</a> for a full list with description. */
  state?: CartAttributesState;
  tax_total?: string;
  /** Used for authorizing actions through the `X-Spree-Order-Token` API Key. */
  token?: string;
  total?: string;
  updated_at?: Timestamp;
};
