/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { CartRelationshipsBillingAddress } from './cartRelationshipsBillingAddress';
import type { CartRelationshipsLineItems } from './cartRelationshipsLineItems';
import type { CartRelationshipsPayments } from './cartRelationshipsPayments';
import type { CartRelationshipsPromotions } from './cartRelationshipsPromotions';
import type { CartRelationshipsShipments } from './cartRelationshipsShipments';
import type { CartRelationshipsShippingAddress } from './cartRelationshipsShippingAddress';
import type { CartRelationshipsUser } from './cartRelationshipsUser';
import type { CartRelationshipsVariants } from './cartRelationshipsVariants';

export type CartRelationships = {
  billing_address?: CartRelationshipsBillingAddress;
  line_items?: CartRelationshipsLineItems;
  payments?: CartRelationshipsPayments;
  promotions?: CartRelationshipsPromotions;
  shipments?: CartRelationshipsShipments;
  shipping_address?: CartRelationshipsShippingAddress;
  user?: CartRelationshipsUser;
  variants?: CartRelationshipsVariants;
};
