/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */

/**
 * State of the Cart in the Checkout flow. Please see <a href="/developer/core-concepts/orders#the-order-state-machine">
  The Order State machine
</a> for a full list with description.
 */
export type CartAttributesState = (typeof CartAttributesState)[keyof typeof CartAttributesState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CartAttributesState = {
  cart: 'cart',
  address: 'address',
  delivery: 'delivery',
  payment: 'payment',
  confirm: 'confirm',
  complete: 'complete'
} as const;
