/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */

/**
 * Overall state of the Shipments. Please see <a href="/developer/core-concepts/orders#order-shipment-states-1">
  Order Shipments states
</a> for a full list with description.
 * @nullable
 */
export type CartAttributesShipmentState =
  | (typeof CartAttributesShipmentState)[keyof typeof CartAttributesShipmentState]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CartAttributesShipmentState = {
  pending: 'pending',
  backorder: 'backorder',
  canceled: 'canceled',
  partial: 'partial',
  ready: 'ready',
  shipped: 'shipped'
} as const;
