/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Authentication
 * Spree uses oAuth based Authentication via short-lived Bearer tokens. You can either create a new one or refresh existing token.
 * OpenAPI spec version: 1.0.0
 */

export type ClientTokenBodyGrantType =
  (typeof ClientTokenBodyGrantType)[keyof typeof ClientTokenBodyGrantType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientTokenBodyGrantType = {
  client_credentials: 'client_credentials'
} as const;
