/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Authentication
 * Spree uses oAuth based Authentication via short-lived Bearer tokens. You can either create a new one or refresh existing token.
 * OpenAPI spec version: 1.0.0
 */
import type { ClientTokenBodyGrantType } from './clientTokenBodyGrantType';

export interface ClientTokenBody {
  /** Use the client id */
  client_id: string;
  /** Client secret key. */
  client_secret: string;
  grant_type: ClientTokenBodyGrantType;
}
