/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { CmsSectionAttributesContent } from './cmsSectionAttributesContent';
import type { CmsSectionAttributesSettings } from './cmsSectionAttributesSettings';

export type CmsSectionAttributes = {
  /** @nullable */
  content?: CmsSectionAttributesContent;
  fit?: string;
  /** @nullable */
  image_one_lg?: string | null;
  /** @nullable */
  image_one_md?: string | null;
  /** @nullable */
  image_one_sm?: string | null;
  /** @nullable */
  image_one_xl?: string | null;
  /** @nullable */
  image_three_lg?: string | null;
  /** @nullable */
  image_three_md?: string | null;
  /** @nullable */
  image_three_sm?: string | null;
  /** @nullable */
  image_three_xl?: string | null;
  /** @nullable */
  image_two_lg?: string | null;
  /** @nullable */
  image_two_md?: string | null;
  /** @nullable */
  image_two_sm?: string | null;
  /** @nullable */
  image_two_xl?: string | null;
  is_full_screen?: boolean;
  /** @nullable */
  link?: string | null;
  name?: string;
  position?: number;
  /** @nullable */
  settings?: CmsSectionAttributesSettings;
  type?: string;
};
