/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { CartIncludeParamParameter } from './cartIncludeParamParameter';
import type { SparseFieldsCartParameter } from './sparseFieldsCartParameter';
import type { PageParamParameter } from './pageParamParameter';
import type { PerPageParamParameter } from './perPageParamParameter';

export type CompletedOrdersParams = {
  /**
   * Specify the related resources you would like to receive in the response body. [More Information](https://jsonapi.org/format/#fetching-includes).
   */
  include?: CartIncludeParamParameter;
  /**
   * Specify the fields you would like returned in the response body. [More information](https://jsonapi.org/format/#fetching-sparse-fieldsets).
   */
  'fields[cart]'?: SparseFieldsCartParameter;
  /**
   * Number of requested page when paginating collection
   */
  page?: PageParamParameter;
  /**
   * Number of requested records per page when paginating collection
   */
  per_page?: PerPageParamParameter;
};
