/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Authentication
 * Spree uses oAuth based Authentication via short-lived Bearer tokens. You can either create a new one or refresh existing token.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTokenBodyGrantType } from './createTokenBodyGrantType';
import type { CreateTokenBodyScope } from './createTokenBodyScope';

export interface CreateTokenBody {
  grant_type: CreateTokenBodyGrantType;
  /** User password */
  password: string;
  /**
   * Pass the value `admin` to create a Platform User Token, allowing access to the Platform API.
   * @nullable
   */
  scope?: CreateTokenBodyScope;
  /** User email address */
  username: string;
}
