/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Authentication
 * Spree uses oAuth based Authentication via short-lived Bearer tokens. You can either create a new one or refresh existing token.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTokenBody } from './createTokenBody';
import type { ClientTokenBody } from './clientTokenBody';
import type { RefreshTokenBody } from './refreshTokenBody';

export type CreateOrRefreshTokenBodyOne = CreateTokenBody | ClientTokenBody | RefreshTokenBody;
