/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Authentication
 * Spree uses oAuth based Authentication via short-lived Bearer tokens. You can either create a new one or refresh existing token.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Pass the value `admin` to create a Platform User Token, allowing access to the Platform API.
 * @nullable
 */
export type CreateTokenBodyScope =
  | (typeof CreateTokenBodyScope)[keyof typeof CreateTokenBodyScope]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTokenBodyScope = {
  admin: 'admin'
} as const;
