/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { CreatePaymentBodySourceAttributesCcType } from './createPaymentBodySourceAttributesCcType';

export type CreatePaymentBodySourceAttributes = {
  cc_type?: CreatePaymentBodySourceAttributesCcType;
  /** Payment source authorization token, more details for [Stripe implementation](https://stripe.com/docs/payments/accept-a-payment-charges#web-create-token) */
  gateway_payment_profile_id: string;
  /** Last 4 digits of CC number */
  last_digits?: string;
  /** Expiration date month */
  month?: number;
  /** Card holder name */
  name: string;
  /** Expiration date year */
  year?: number;
};
