/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { WishlistIncludeParamParameter } from './wishlistIncludeParamParameter';
import type { SparseFieldsWishlistParameter } from './sparseFieldsWishlistParameter';
import type { WishlistIsVariantIncludedParamParameter } from './wishlistIsVariantIncludedParamParameter';

export type GetDefaultWishlistParams = {
  /**
   * Specify the related resources you would like to receive in the `included` section of the response body. You can also retrieve related resources of included resources by using the dot notation, eg. `wished_items.variant`. [More information](https://jsonapi.org/format/#fetching-includes).
   */
  include?: WishlistIncludeParamParameter;
  /**
   * Specify the fields you would like returned in the response body. [More information](https://jsonapi.org/format/#fetching-sparse-fieldsets).
   */
  'fields[wishlist]'?: SparseFieldsWishlistParameter;
  /**
   * Check for the presence of a variant in a wishlist by passing the variant ID, if the variant is present in the wishlist, the `variant_included` attribute will return `true`
   */
  is_variant_included?: WishlistIsVariantIncludedParamParameter;
};
