/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { FilterByLocationParameter } from './filterByLocationParameter';
import type { MenuIncludeParamParameter } from './menuIncludeParamParameter';
import type { LocaleParamParameter } from './localeParamParameter';
import type { PerPageParamParameter } from './perPageParamParameter';

export type GetMenusParams = {
  /**
   * Fetch only resources with corresponding Location
   */
  'filter[location]'?: FilterByLocationParameter;
  /**
   * Pass `menu_items` as an include value to fetch the Menu Items associated with each Menu. If you need to fetch the Menu Item Linked Resource, you can pass `menu_items.linked_resource`, additionally, you can pass `menu_items.icon` to fetch the associated Icon for each menu Item
   */
  include?: MenuIncludeParamParameter;
  /**
   * Pass `locale` as value to fetch the resources with the matching locale for example `?locale=fr`.
   */
  locale?: LocaleParamParameter;
  /**
   * Number of requested records per page when paginating collection
   */
  per_page?: PerPageParamParameter;
};
