/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { MenuItemRelationshipsChildren } from './menuItemRelationshipsChildren';
import type { MenuItemRelationshipsIcon } from './menuItemRelationshipsIcon';
import type { MenuItemRelationshipsLinkedResource } from './menuItemRelationshipsLinkedResource';
import type { MenuItemRelationshipsMenu } from './menuItemRelationshipsMenu';
import type { MenuItemRelationshipsParent } from './menuItemRelationshipsParent';

export type MenuItemRelationships = {
  /** List of child nodes */
  children?: MenuItemRelationshipsChildren;
  /** Icon associated with Menu Item */
  icon?: MenuItemRelationshipsIcon;
  /** Linked Resource associated with this Menu Item */
  linked_resource?: MenuItemRelationshipsLinkedResource;
  /** Menu associated with this Menu Item */
  menu?: MenuItemRelationshipsMenu;
  /** Parent node */
  parent?: MenuItemRelationshipsParent;
};
