/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Authentication
 * Spree uses oAuth based Authentication via short-lived Bearer tokens. You can either create a new one or refresh existing token.
 * OpenAPI spec version: 1.0.0
 */
import type { RefreshTokenBodyGrantType } from './refreshTokenBodyGrantType';

export interface RefreshTokenBody {
  grant_type: RefreshTokenBodyGrantType;
  /** Refresh token obtained from the create token response */
  refresh_token: string;
}
