/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */

export type ShippingRateAttributes = {
  /** Price of the service without discounts applied */
  cost?: string;
  display_cost?: string;
  display_final_price?: string;
  display_tax_amount?: string;
  /** Price to be presented for the Customer */
  final_price?: string;
  /** Indicates if the Shipping Rate is free, eg. when Free shipping promo applied to Cart */
  free?: boolean;
  name?: string;
  selected?: boolean;
  /** ID of a Shipping Method. You will need this for the Checkout Update action */
  shipping_method_id?: number;
  /** Eligible tax for service (if any) */
  tax_amount?: string;
};
