/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { ShipmentAttributesState } from './shipmentAttributesState';

export type ShipmentAttributes = {
  display_final_price?: string;
  /** Price to be presented for the Customer */
  final_price?: string;
  /** Indicates if the Shipping Rate is free, eg. when Free shipping promo applied to Cart */
  free?: boolean;
  /** Unique Shipment identifier */
  number?: string;
  /**
   * Date when Shipment was being sent from the warehouse
   * @nullable
   */
  shipped_at?: string | null;
  /** Status of the Shipment. For a list of all available statuses please refer: <a href="/developer/core-concepts/shipments" target="_blank" rel="noopener">
  Shipment section in Spree Guides
</a> */
  state?: ShipmentAttributesState;
  /**
   * Tracking URL to the service provider website
   * @nullable
   */
  tracking_url?: string | null;
};
