/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { ProductIncludeParamParameter } from './productIncludeParamParameter';
import type { SparseFieldsProductParameter } from './sparseFieldsProductParameter';
import type { ProductImageTransformationSizeParamParameter } from './productImageTransformationSizeParamParameter';
import type { ProductImageTransformationQualityParamParameter } from './productImageTransformationQualityParamParameter';

export type ShowProductParams = {
  /**
 * Specify what related resources (relationships) you would like to receive in the response body. Eg.

```
default_variant,variants,option_types,product_properties,taxons,images,primary_variant
```

[More information](https://jsonapi.org/format/#fetching-includes)
 */
  include?: ProductIncludeParamParameter;
  /**
   * Specify the fields you would like returned in the response body. [More information](https://jsonapi.org/format/#fetching-sparse-fieldsets).
   */
  'fields[product]'?: SparseFieldsProductParameter;
  /**
   * Specifies dimensions for included images at transformed_url attribute.
   */
  'image_transformation[size]'?: ProductImageTransformationSizeParamParameter;
  /**
   * Specifies quality for included images at transformed_url attribute
   */
  'image_transformation[quality]'?: ProductImageTransformationQualityParamParameter;
};
