/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { TaxonAttributesLocalizedSlugs } from './taxonAttributesLocalizedSlugs';

export type TaxonAttributes = {
  /** @nullable */
  depth?: number | null;
  /** Returns true is this is a child node of this Taxonomy tree */
  is_child?: boolean;
  /** Returns true if this is the end of a branch of this Taxonomy tree */
  is_leaf?: boolean;
  /** Indicates if the Taxon is the root node of this Taxonomy tree */
  is_root?: boolean;
  left?: number;
  /** Provides taxon's slugs in other locales */
  localized_slugs?: TaxonAttributesLocalizedSlugs;
  /** @nullable */
  meta_description?: string | null;
  /** @nullable */
  meta_keywords?: string | null;
  /** @nullable */
  meta_title?: string | null;
  name?: string;
  permalink?: string;
  position?: number;
  pretty_name?: string;
  right?: number;
  seo_title?: string;
  updated_at?: string;
};
