/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Authentication
 * Spree uses oAuth based Authentication via short-lived Bearer tokens. You can either create a new one or refresh existing token.
 * OpenAPI spec version: 1.0.0
 */

export interface Token {
  access_token: string;
  created_at: number;
  /** Time (in seconds) after which the access token will expire */
  expires_in: number;
  refresh_token: string;
  scope?: string;
  token_type: string;
}
