/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { AddressPayload } from './addressPayload';
import type { UpdateCheckoutBodyOrderPaymentsAttributesItem } from './updateCheckoutBodyOrderPaymentsAttributesItem';
import type { UpdateCheckoutBodyOrderShipmentsAttributesItem } from './updateCheckoutBodyOrderShipmentsAttributesItem';

export type UpdateCheckoutBodyOrder = {
  bill_address_attributes?: AddressPayload;
  email?: string;
  payments_attributes?: UpdateCheckoutBodyOrderPaymentsAttributesItem[];
  ship_address_attributes?: AddressPayload;
  shipments_attributes?: UpdateCheckoutBodyOrderShipmentsAttributesItem[];
};
