/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';
import type {
  CartResponse,
  NotFoundResponse,
  UnprocessableEntityResponse,
  UpdateCheckoutBody,
  UpdateCheckoutParams
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';
import type { BodyType } from '../../../config/custom-instance';

/**
 * The Update Checkout endpoint allows you to manage the typical stages of an e-commerce checkout system.
 * @summary Update Checkout
 */
export const updateCheckout = (
  updateCheckoutBody: BodyType<UpdateCheckoutBody>,
  params?: UpdateCheckoutParams
) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/checkout`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: updateCheckoutBody,
    params
  });
};

export const getUpdateCheckoutMutationOptions = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCheckout>>,
    TError,
    { data: BodyType<UpdateCheckoutBody>; params?: UpdateCheckoutParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCheckout>>,
  TError,
  { data: BodyType<UpdateCheckoutBody>; params?: UpdateCheckoutParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCheckout>>,
    { data: BodyType<UpdateCheckoutBody>; params?: UpdateCheckoutParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return updateCheckout(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCheckoutMutationResult = NonNullable<Awaited<ReturnType<typeof updateCheckout>>>;
export type UpdateCheckoutMutationBody = BodyType<UpdateCheckoutBody>;
export type UpdateCheckoutMutationError = NotFoundResponse | UnprocessableEntityResponse;

/**
 * @summary Update Checkout
 */
export const useUpdateCheckout = <
  TError = NotFoundResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCheckout>>,
    TError,
    { data: BodyType<UpdateCheckoutBody>; params?: UpdateCheckoutParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateCheckout>>,
  TError,
  { data: BodyType<UpdateCheckoutBody>; params?: UpdateCheckoutParams },
  TContext
> => {
  const mutationOptions = getUpdateCheckoutMutationOptions(options);

  return useMutation(mutationOptions);
};
