/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  AccountCreationBody,
  AccountInformationParams,
  AccountUpdatesBody,
  ForbiddenResponse,
  UnprocessableEntityResponse,
  UserResponse
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';
import type { BodyType } from '../../../config/custom-instance';

/**
 * Returns the current user details.
 * @summary Retrieve an Account
 */
export const accountInformation = (params?: AccountInformationParams, signal?: AbortSignal) => {
  return customInstance<UserResponse>({
    url: `/api/v2/storefront/account`,
    method: 'GET',
    params,
    signal
  });
};

export const getAccountInformationQueryKey = (params?: AccountInformationParams) => {
  return [`/api/v2/storefront/account`, ...(params ? [params] : [])] as const;
};

export const getAccountInformationQueryOptions = <
  TData = Awaited<ReturnType<typeof accountInformation>>,
  TError = ForbiddenResponse
>(
  params?: AccountInformationParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountInformation>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAccountInformationQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof accountInformation>>> = ({ signal }) =>
    accountInformation(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof accountInformation>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AccountInformationQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountInformation>>
>;
export type AccountInformationQueryError = ForbiddenResponse;

/**
 * @summary Retrieve an Account
 */
export const useAccountInformation = <
  TData = Awaited<ReturnType<typeof accountInformation>>,
  TError = ForbiddenResponse
>(
  params?: AccountInformationParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountInformation>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountInformationQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAccountInformationSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof accountInformation>>,
  TError = ForbiddenResponse
>(
  params?: AccountInformationParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof accountInformation>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAccountInformationQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof accountInformation>>> = ({ signal }) =>
    accountInformation(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof accountInformation>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AccountInformationSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountInformation>>
>;
export type AccountInformationSuspenseQueryError = ForbiddenResponse;

/**
 * @summary Retrieve an Account
 */
export const useAccountInformationSuspense = <
  TData = Awaited<ReturnType<typeof accountInformation>>,
  TError = ForbiddenResponse
>(
  params?: AccountInformationParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof accountInformation>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountInformationSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Creates a new account. This endpoint requires the [Spree Auth Devise](https://github.com/spree/spree_auth_devise) gem to be installed.
 * @summary Create an Account
 */
export const accountCreation = (accountCreationBody: BodyType<AccountCreationBody>) => {
  return customInstance<UserResponse>({
    url: `/api/v2/storefront/account`,
    method: 'POST',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: accountCreationBody
  });
};

export const getAccountCreationMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountCreation>>,
    TError,
    { data: BodyType<AccountCreationBody> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountCreation>>,
  TError,
  { data: BodyType<AccountCreationBody> },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountCreation>>,
    { data: BodyType<AccountCreationBody> }
  > = (props) => {
    const { data } = props ?? {};

    return accountCreation(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountCreationMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountCreation>>
>;
export type AccountCreationMutationBody = BodyType<AccountCreationBody>;
export type AccountCreationMutationError = UnprocessableEntityResponse;

/**
 * @summary Create an Account
 */
export const useAccountCreation = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountCreation>>,
    TError,
    { data: BodyType<AccountCreationBody> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof accountCreation>>,
  TError,
  { data: BodyType<AccountCreationBody> },
  TContext
> => {
  const mutationOptions = getAccountCreationMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Updates the users account details. This endpoint requires the [Spree Auth Devise](https://github.com/spree/spree_auth_devise) gem to be installed.
 * @summary Update an Account
 */
export const accountUpdates = (accountUpdatesBody: BodyType<AccountUpdatesBody>) => {
  return customInstance<UserResponse>({
    url: `/api/v2/storefront/account`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: accountUpdatesBody
  });
};

export const getAccountUpdatesMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountUpdates>>,
    TError,
    { data: BodyType<AccountUpdatesBody> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountUpdates>>,
  TError,
  { data: BodyType<AccountUpdatesBody> },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountUpdates>>,
    { data: BodyType<AccountUpdatesBody> }
  > = (props) => {
    const { data } = props ?? {};

    return accountUpdates(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountUpdatesMutationResult = NonNullable<Awaited<ReturnType<typeof accountUpdates>>>;
export type AccountUpdatesMutationBody = BodyType<AccountUpdatesBody>;
export type AccountUpdatesMutationError = UnprocessableEntityResponse;

/**
 * @summary Update an Account
 */
export const useAccountUpdates = <
  TError = UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountUpdates>>,
    TError,
    { data: BodyType<AccountUpdatesBody> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof accountUpdates>>,
  TError,
  { data: BodyType<AccountUpdatesBody> },
  TContext
> => {
  const mutationOptions = getAccountUpdatesMutationOptions(options);

  return useMutation(mutationOptions);
};
