/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  AssociateCartParams,
  CartResponse,
  ChangeCurrencyParams,
  EmptyCartParams,
  EstimateShippingRatesParams,
  EstimatedShippingRatesResponse,
  ForbiddenResponse,
  NotFoundResponse,
  UnprocessableEntityResponse
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';

/**
 * This endpoint removed all line items from the cart. Inventory that was previously taken by this order will be re-stocked.
 * @summary Empty the Cart
 */
export const emptyCart = (params?: EmptyCartParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart/empty`,
    method: 'PATCH',
    params
  });
};

export const getEmptyCartMutationOptions = <
  TError = NotFoundResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof emptyCart>>,
    TError,
    { params?: EmptyCartParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof emptyCart>>,
  TError,
  { params?: EmptyCartParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof emptyCart>>,
    { params?: EmptyCartParams }
  > = (props) => {
    const { params } = props ?? {};

    return emptyCart(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmptyCartMutationResult = NonNullable<Awaited<ReturnType<typeof emptyCart>>>;

export type EmptyCartMutationError = NotFoundResponse;

/**
 * @summary Empty the Cart
 */
export const useEmptyCart = <TError = NotFoundResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof emptyCart>>,
    TError,
    { params?: EmptyCartParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof emptyCart>>,
  TError,
  { params?: EmptyCartParams },
  TContext
> => {
  const mutationOptions = getEmptyCartMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Returns a list of shipping rates for the current cart. The rates given are only estimates and can vary from the final shipping rates.
 * @summary List Estimated Shipping Rates
 */
export const estimateShippingRates = (
  params: EstimateShippingRatesParams,
  signal?: AbortSignal
) => {
  return customInstance<EstimatedShippingRatesResponse>({
    url: `/api/v2/storefront/cart/estimate_shipping_rates`,
    method: 'GET',
    params,
    signal
  });
};

export const getEstimateShippingRatesQueryKey = (params: EstimateShippingRatesParams) => {
  return [`/api/v2/storefront/cart/estimate_shipping_rates`, ...(params ? [params] : [])] as const;
};

export const getEstimateShippingRatesQueryOptions = <
  TData = Awaited<ReturnType<typeof estimateShippingRates>>,
  TError = NotFoundResponse
>(
  params: EstimateShippingRatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof estimateShippingRates>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEstimateShippingRatesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof estimateShippingRates>>> = ({ signal }) =>
    estimateShippingRates(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof estimateShippingRates>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type EstimateShippingRatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof estimateShippingRates>>
>;
export type EstimateShippingRatesQueryError = NotFoundResponse;

/**
 * @summary List Estimated Shipping Rates
 */
export const useEstimateShippingRates = <
  TData = Awaited<ReturnType<typeof estimateShippingRates>>,
  TError = NotFoundResponse
>(
  params: EstimateShippingRatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof estimateShippingRates>>, TError, TData>
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getEstimateShippingRatesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getEstimateShippingRatesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof estimateShippingRates>>,
  TError = NotFoundResponse
>(
  params: EstimateShippingRatesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof estimateShippingRates>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEstimateShippingRatesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof estimateShippingRates>>> = ({ signal }) =>
    estimateShippingRates(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof estimateShippingRates>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type EstimateShippingRatesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof estimateShippingRates>>
>;
export type EstimateShippingRatesSuspenseQueryError = NotFoundResponse;

/**
 * @summary List Estimated Shipping Rates
 */
export const useEstimateShippingRatesSuspense = <
  TData = Awaited<ReturnType<typeof estimateShippingRates>>,
  TError = NotFoundResponse
>(
  params: EstimateShippingRatesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof estimateShippingRates>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getEstimateShippingRatesSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Associates a guest cart with the currently signed in user.
 * @summary Associate a Cart with a User
 */
export const associateCart = (params: AssociateCartParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart/associate`,
    method: 'PATCH',
    params
  });
};

export const getAssociateCartMutationOptions = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof associateCart>>,
    TError,
    { params: AssociateCartParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof associateCart>>,
  TError,
  { params: AssociateCartParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof associateCart>>,
    { params: AssociateCartParams }
  > = (props) => {
    const { params } = props ?? {};

    return associateCart(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssociateCartMutationResult = NonNullable<Awaited<ReturnType<typeof associateCart>>>;

export type AssociateCartMutationError = ForbiddenResponse | UnprocessableEntityResponse;

/**
 * @summary Associate a Cart with a User
 */
export const useAssociateCart = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof associateCart>>,
    TError,
    { params: AssociateCartParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof associateCart>>,
  TError,
  { params: AssociateCartParams },
  TContext
> => {
  const mutationOptions = getAssociateCartMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Changes the cart currency and recalculates the cart values.
 * @summary Change Cart Currency
 */
export const changeCurrency = (params: ChangeCurrencyParams) => {
  return customInstance<CartResponse>({
    url: `/api/v2/storefront/cart/change_currency`,
    method: 'PATCH',
    params
  });
};

export const getChangeCurrencyMutationOptions = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeCurrency>>,
    TError,
    { params: ChangeCurrencyParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof changeCurrency>>,
  TError,
  { params: ChangeCurrencyParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changeCurrency>>,
    { params: ChangeCurrencyParams }
  > = (props) => {
    const { params } = props ?? {};

    return changeCurrency(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChangeCurrencyMutationResult = NonNullable<Awaited<ReturnType<typeof changeCurrency>>>;

export type ChangeCurrencyMutationError = ForbiddenResponse | UnprocessableEntityResponse;

/**
 * @summary Change Cart Currency
 */
export const useChangeCurrency = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeCurrency>>,
    TError,
    { params: ChangeCurrencyParams },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof changeCurrency>>,
  TError,
  { params: ChangeCurrencyParams },
  TContext
> => {
  const mutationOptions = getChangeCurrencyMutationOptions(options);

  return useMutation(mutationOptions);
};
