/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  CmsPageListResponse,
  CmsPageResponse,
  GetCmsPageParams,
  GetCmsPagesParams,
  NotFoundResponse
} from '.././schema';
import { customInstance } from '../../config/custom-instance';

/**
 * Returns a list of all CMS Pages available in the current store.
 * @summary List all CMS Pages
 */
export const getCmsPages = (params?: GetCmsPagesParams, signal?: AbortSignal) => {
  return customInstance<CmsPageListResponse>({
    url: `/api/v2/storefront/cms_pages`,
    method: 'GET',
    params,
    signal
  });
};

export const getGetCmsPagesQueryKey = (params?: GetCmsPagesParams) => {
  return [`/api/v2/storefront/cms_pages`, ...(params ? [params] : [])] as const;
};

export const getGetCmsPagesQueryOptions = <
  TData = Awaited<ReturnType<typeof getCmsPages>>,
  TError = NotFoundResponse
>(
  params?: GetCmsPagesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCmsPages>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCmsPagesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCmsPages>>> = ({ signal }) =>
    getCmsPages(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCmsPages>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCmsPagesQueryResult = NonNullable<Awaited<ReturnType<typeof getCmsPages>>>;
export type GetCmsPagesQueryError = NotFoundResponse;

/**
 * @summary List all CMS Pages
 */
export const useGetCmsPages = <
  TData = Awaited<ReturnType<typeof getCmsPages>>,
  TError = NotFoundResponse
>(
  params?: GetCmsPagesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCmsPages>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCmsPagesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetCmsPagesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCmsPages>>,
  TError = NotFoundResponse
>(
  params?: GetCmsPagesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCmsPages>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCmsPagesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCmsPages>>> = ({ signal }) =>
    getCmsPages(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCmsPages>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCmsPagesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getCmsPages>>>;
export type GetCmsPagesSuspenseQueryError = NotFoundResponse;

/**
 * @summary List all CMS Pages
 */
export const useGetCmsPagesSuspense = <
  TData = Awaited<ReturnType<typeof getCmsPages>>,
  TError = NotFoundResponse
>(
  params?: GetCmsPagesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCmsPages>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCmsPagesSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * To return a single CMS Page you can use the CMS Page slug:

```
GET /api/v2/storefront/cms_pages/about-us
```

or CMS Page ID:

```
GET /api/v2/storefront/cms_pages/37
```

**Note:** API will attempt a Slug lookup before an ID lookup.
 * @summary Retrieve a CMS Page
 */
export const getCmsPage = (
  cmsPageSlug: string,
  params?: GetCmsPageParams,
  signal?: AbortSignal
) => {
  return customInstance<CmsPageResponse>({
    url: `/api/v2/storefront/cms_pages/${cmsPageSlug}`,
    method: 'GET',
    params,
    signal
  });
};

export const getGetCmsPageQueryKey = (cmsPageSlug: string, params?: GetCmsPageParams) => {
  return [`/api/v2/storefront/cms_pages/${cmsPageSlug}`, ...(params ? [params] : [])] as const;
};

export const getGetCmsPageQueryOptions = <
  TData = Awaited<ReturnType<typeof getCmsPage>>,
  TError = NotFoundResponse
>(
  cmsPageSlug: string,
  params?: GetCmsPageParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCmsPage>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCmsPageQueryKey(cmsPageSlug, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCmsPage>>> = ({ signal }) =>
    getCmsPage(cmsPageSlug, params, signal);

  return { queryKey, queryFn, enabled: !!cmsPageSlug, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCmsPage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCmsPageQueryResult = NonNullable<Awaited<ReturnType<typeof getCmsPage>>>;
export type GetCmsPageQueryError = NotFoundResponse;

/**
 * @summary Retrieve a CMS Page
 */
export const useGetCmsPage = <
  TData = Awaited<ReturnType<typeof getCmsPage>>,
  TError = NotFoundResponse
>(
  cmsPageSlug: string,
  params?: GetCmsPageParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCmsPage>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCmsPageQueryOptions(cmsPageSlug, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetCmsPageSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCmsPage>>,
  TError = NotFoundResponse
>(
  cmsPageSlug: string,
  params?: GetCmsPageParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCmsPage>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCmsPageQueryKey(cmsPageSlug, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCmsPage>>> = ({ signal }) =>
    getCmsPage(cmsPageSlug, params, signal);

  return { queryKey, queryFn, enabled: !!cmsPageSlug, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCmsPage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCmsPageSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getCmsPage>>>;
export type GetCmsPageSuspenseQueryError = NotFoundResponse;

/**
 * @summary Retrieve a CMS Page
 */
export const useGetCmsPageSuspense = <
  TData = Awaited<ReturnType<typeof getCmsPage>>,
  TError = NotFoundResponse
>(
  cmsPageSlug: string,
  params?: GetCmsPageParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCmsPage>>, TError, TData>>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCmsPageSuspenseQueryOptions(cmsPageSlug, params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
