/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { AccountCreationBodyUserPrivateMetadata } from './accountCreationBodyUserPrivateMetadata';
import type { AccountCreationBodyUserPublicMetadata } from './accountCreationBodyUserPublicMetadata';

export type AccountCreationBodyUser = {
  email?: string;
  first_name?: string;
  last_name?: string;
  password?: string;
  password_confirmation?: string;
  /** The private metadata for this User */
  private_metadata?: AccountCreationBodyUserPrivateMetadata;
  /** The public metadata for this User */
  public_metadata?: AccountCreationBodyUserPublicMetadata;
  selected_locale?: string;
};
