/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { FilterByTypeParameter } from './filterByTypeParameter';
import type { FilterByTitleParameter } from './filterByTitleParameter';
import type { CmsPageIncludeParamParameter } from './cmsPageIncludeParamParameter';
import type { PerPageParamParameter } from './perPageParamParameter';

export type GetCmsPagesParams = {
  /**
   * Fetch only resources with corresponding Type
   */
  'filter[type]'?: FilterByTypeParameter;
  /**
   * Fetch only resources with correspondingTitle
   */
  'filter[title]'?: FilterByTitleParameter;
  /**
   * Pass `cms_sections` as an include value to fetch the CMS Sections associated with each CMS Page. If you need to fetch the CMS Sections Linked Resource, you can pass `cms_sections.linked_resource`.
   */
  include?: CmsPageIncludeParamParameter;
  /**
   * Number of requested records per page when paginating collection
   */
  per_page?: PerPageParamParameter;
};
