/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { LineItemAttributesPublicMetadata } from './lineItemAttributesPublicMetadata';

export type LineItemAttributes = {
  additional_tax_total?: string;
  /** TBD */
  adjustment_total?: string;
  currency?: string;
  discounted_amount?: string;
  display_additional_tax_total?: string;
  /** TBD */
  display_adjustment_total?: string;
  display_discounted_amount?: string;
  display_inluded_tax_total?: string;
  display_pre_tax_amount?: string;
  /** Price of Product per quantity */
  display_price?: string;
  display_promo_total?: string;
  /** Total price of Line Item including adjastments, promotions and taxes */
  display_total?: string;
  /** Taxes included in the price, eg. VAT */
  included_tax_total?: string;
  name?: string;
  options_text?: string;
  pre_tax_amount?: string;
  /** Price of Product per quantity */
  price?: string;
  promo_total?: string;
  /** The public metadata for the Line Item. */
  public_metadata?: LineItemAttributesPublicMetadata;
  quantity?: number;
  slug?: string;
  /** Total price of Line Item including adjastments, promotions and taxes */
  total?: string;
};
