/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */

/**
 * Pass `menu_items` as an include value to fetch the Menu Items associated with each Menu. If you need to fetch the Menu Item Linked Resource, you can pass `menu_items.linked_resource`, additionally, you can pass `menu_items.icon` to fetch the associated Icon for each menu Item
 */
export type MenuIncludeParamParameter = string;
