/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { ProductRelationshipsDefaultVariant } from './productRelationshipsDefaultVariant';
import type { ProductRelationshipsImages } from './productRelationshipsImages';
import type { ProductRelationshipsOptionTypes } from './productRelationshipsOptionTypes';
import type { ProductRelationshipsPrimaryVariant } from './productRelationshipsPrimaryVariant';
import type { ProductRelationshipsProductProperties } from './productRelationshipsProductProperties';
import type { ProductRelationshipsTaxons } from './productRelationshipsTaxons';
import type { ProductRelationshipsVariants } from './productRelationshipsVariants';

export type ProductRelationships = {
  /** The default Variant for this product */
  default_variant?: ProductRelationshipsDefaultVariant;
  /** List of Images associated with this Product */
  images?: ProductRelationshipsImages;
  /** List of Product Option Types */
  option_types?: ProductRelationshipsOptionTypes;
  /** The Primary Variant for this product */
  primary_variant?: ProductRelationshipsPrimaryVariant;
  /** List of Product Properties */
  product_properties?: ProductRelationshipsProductProperties;
  /** List of Taxons associated with this Product */
  taxons?: ProductRelationshipsTaxons;
  /** List of Product Variants, excluding Master Variant */
  variants?: ProductRelationshipsVariants;
};
