/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { FilterByIdsParameter } from './filterByIdsParameter';
import type { FilterBySKUsParameter } from './filterBySKUsParameter';
import type { PageParamParameter } from './pageParamParameter';
import type { PerPageParamParameter } from './perPageParamParameter';
import type { ProductIncludeParamParameter } from './productIncludeParamParameter';
import type { SparseFieldsProductParameter } from './sparseFieldsProductParameter';
import type { ProductImageTransformationSizeParamParameter } from './productImageTransformationSizeParamParameter';
import type { ProductImageTransformationQualityParamParameter } from './productImageTransformationQualityParamParameter';

export type ProductsListParams = {
  /**
   * Fetch only resources with corresponding IDs
   */
  'filter[ids]'?: FilterByIdsParameter;
  /**
   * Fetch only resources with corresponding SKUs
   */
  'filter[skus]'?: FilterBySKUsParameter;
  /**
   * Filter Products based on price (minimum, maximum range)
   */
  'filter[price]'?: string;
  /**
   * Filter Products based on taxons (IDs of categories, brands, etc)
   */
  'filter[taxons]'?: string;
  /**
   * Find Products with matching name (supports wild-card, partial-word match search)
   */
  'filter[name]'?: string;
  /**
   * Find Products with Variants that have the specified option (eg. color, size) and value (eg. red, XS)
   */
  'filter[options][tshirt-color]'?: string;
  /**
   * Find Products with Property Brand Name with value Alpha
   */
  'filter[properties][brand-name]'?: string;
  /**
   * Returns also deleted products
   */
  'filter[show_deleted]'?: boolean;
  /**
   * Returns also discontinued products
   */
  'filter[show_discontinued]'?: boolean;
  /**
   * Returns only in stock products
   */
  'filter[in_stock]'?: boolean;
  /**
   * Returns only backorderable products
   */
  'filter[backorderable]'?: boolean;
  /**
   * Returns only in stock or backorderable products
   */
  'filter[purchasable]'?: boolean;
  /**
 * Sort products based on: <ul>
  <li>name (ascending/descending)</li>
  <li>price (ascending/descending)</li>
  <li>available_on (ascending/descending)</li>
  <li>created_at (ascending/descending)</li>
  <li>updated_at (ascending/descending)</li>
  <li>sku (ascending/descending)</li>
</ul> Use <q>-</q> sign to set descending sort, eg. <q>-updated_at</q>
 */
  sort?: string;
  /**
   * Number of requested page when paginating collection
   */
  page?: PageParamParameter;
  /**
   * Number of requested records per page when paginating collection
   */
  per_page?: PerPageParamParameter;
  /**
 * Specify what related resources (relationships) you would like to receive in the response body. Eg.

```
default_variant,variants,option_types,product_properties,taxons,images,primary_variant
```

[More information](https://jsonapi.org/format/#fetching-includes)
 */
  include?: ProductIncludeParamParameter;
  /**
   * Specify the fields you would like returned in the response body. [More information](https://jsonapi.org/format/#fetching-sparse-fieldsets).
   */
  'fields[product]'?: SparseFieldsProductParameter;
  /**
   * Specifies dimensions for included images at transformed_url attribute.
   */
  'image_transformation[size]'?: ProductImageTransformationSizeParamParameter;
  /**
   * Specifies quality for included images at transformed_url attribute
   */
  'image_transformation[quality]'?: ProductImageTransformationQualityParamParameter;
};
