/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import type { ProductAttributesLocalizedSlugs } from './productAttributesLocalizedSlugs';
import type { Timestamp } from './timestamp';

export type ProductAttributes = {
  available?: boolean;
  /** @nullable */
  available_on?: string | null;
  /** Indicates if any of Variants are backeorderable */
  backorderable?: boolean;
  /** @nullable */
  compare_at_price?: string | null;
  currency?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  display_compare_at_price?: string | null;
  /** @nullable */
  display_price?: string | null;
  /** Indicates if any of Variants are in stock */
  in_stock?: boolean;
  /** Provides product's slugs in other locales */
  localized_slugs?: ProductAttributesLocalizedSlugs;
  /** @nullable */
  meta_description?: string | null;
  /** @nullable */
  meta_keywords?: string | null;
  name?: string;
  /** @nullable */
  price?: string | null;
  /** Indicates if any of Variants are in stock or backorderable */
  purchasable?: boolean;
  sku?: string;
  slug?: string;
  updated_at?: Timestamp;
};
