/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */

export type StoreAttributes = {
  /** Address of the Store which is visible in the Footer */
  address?: string;
  /** Contact phone number of the Store which is visible in the Footer */
  contact_phone?: string;
  /** This email is visible to your Store visitors in the Footer section */
  customer_support_email?: string;
  /** Indicates if the Store is the default one */
  default?: boolean;
  /** Default currency of the store */
  default_currency?: string;
  /** Default locale of the Store */
  default_locale?: string;
  /** Description of the Store which is visible in the Footer */
  description?: string;
  /** URL of Facebook page */
  facebook?: string;
  favicon_path?: string;
  /** URL of Instagram page */
  instagram?: string;
  /** Meta description for SEO */
  meta_description?: string;
  /** Meta keywords for SEO */
  meta_keywords?: string;
  /** Name of the Store */
  name?: string;
  /** The title for SEO */
  seo_title?: string;
  /** All currencies supported by store */
  supported_currencies?: string;
  /** Supported locales of the Store */
  supported_locales?: string;
  /** URL of Twitter page */
  twitter?: string;
  /** Store Url */
  url?: string;
};
