/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';
import type {
  AddItemToWishlistBody,
  ForbiddenResponse,
  UnprocessableEntityResponse,
  UpdateWishedVariantQuantityBody,
  WishedItemResponse
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';
import type { BodyType } from '../../../config/custom-instance';

/**
 * The Add Item to Wishlist endpoint adds a variant to an existing wishlist by creating a new `wished_item`. A wished item in a wishlist is comparable to a line item in a cart.

Each wished item references a single variant, holds the desired quantity and returns price information determined by the variant price in current currency, and desired quantity.
 * @summary Add Item to Wishlist
 */
export const addItemToWishlist = (
  token: string,
  addItemToWishlistBody: BodyType<AddItemToWishlistBody>
) => {
  return customInstance<WishedItemResponse>({
    url: `/api/v2/storefront/wishlists/${token}/add_item`,
    method: 'POST',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: addItemToWishlistBody
  });
};

export const getAddItemToWishlistMutationOptions = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addItemToWishlist>>,
    TError,
    { token: string; data: BodyType<AddItemToWishlistBody> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addItemToWishlist>>,
  TError,
  { token: string; data: BodyType<AddItemToWishlistBody> },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addItemToWishlist>>,
    { token: string; data: BodyType<AddItemToWishlistBody> }
  > = (props) => {
    const { token, data } = props ?? {};

    return addItemToWishlist(token, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddItemToWishlistMutationResult = NonNullable<
  Awaited<ReturnType<typeof addItemToWishlist>>
>;
export type AddItemToWishlistMutationBody = BodyType<AddItemToWishlistBody>;
export type AddItemToWishlistMutationError = ForbiddenResponse | UnprocessableEntityResponse;

/**
 * @summary Add Item to Wishlist
 */
export const useAddItemToWishlist = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addItemToWishlist>>,
    TError,
    { token: string; data: BodyType<AddItemToWishlistBody> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof addItemToWishlist>>,
  TError,
  { token: string; data: BodyType<AddItemToWishlistBody> },
  TContext
> => {
  const mutationOptions = getAddItemToWishlistMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * This endpoint sets the wished item quantity.
 * @summary Set Wished Item Quantity
 */
export const updateWishedVariantQuantity = (
  token: string,
  itemId: string,
  updateWishedVariantQuantityBody: BodyType<UpdateWishedVariantQuantityBody>
) => {
  return customInstance<WishedItemResponse>({
    url: `/api/v2/storefront/wishlists/${token}/set_item_quantity/${itemId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/vnd.api+json' },
    data: updateWishedVariantQuantityBody
  });
};

export const getUpdateWishedVariantQuantityMutationOptions = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateWishedVariantQuantity>>,
    TError,
    { token: string; itemId: string; data: BodyType<UpdateWishedVariantQuantityBody> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateWishedVariantQuantity>>,
  TError,
  { token: string; itemId: string; data: BodyType<UpdateWishedVariantQuantityBody> },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateWishedVariantQuantity>>,
    { token: string; itemId: string; data: BodyType<UpdateWishedVariantQuantityBody> }
  > = (props) => {
    const { token, itemId, data } = props ?? {};

    return updateWishedVariantQuantity(token, itemId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateWishedVariantQuantityMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateWishedVariantQuantity>>
>;
export type UpdateWishedVariantQuantityMutationBody = BodyType<UpdateWishedVariantQuantityBody>;
export type UpdateWishedVariantQuantityMutationError =
  | ForbiddenResponse
  | UnprocessableEntityResponse;

/**
 * @summary Set Wished Item Quantity
 */
export const useUpdateWishedVariantQuantity = <
  TError = ForbiddenResponse | UnprocessableEntityResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateWishedVariantQuantity>>,
    TError,
    { token: string; itemId: string; data: BodyType<UpdateWishedVariantQuantityBody> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateWishedVariantQuantity>>,
  TError,
  { token: string; itemId: string; data: BodyType<UpdateWishedVariantQuantityBody> },
  TContext
> => {
  const mutationOptions = getUpdateWishedVariantQuantityMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Removes a wished item from a wishlist.
 * @summary Delete Item from Wishlist
 */
export const deleteWishedVariantFromWishlist = (token: string, itemId: string) => {
  return customInstance<WishedItemResponse>({
    url: `/api/v2/storefront/wishlists/${token}/remove_item/${itemId}`,
    method: 'DELETE'
  });
};

export const getDeleteWishedVariantFromWishlistMutationOptions = <
  TError = ForbiddenResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteWishedVariantFromWishlist>>,
    TError,
    { token: string; itemId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteWishedVariantFromWishlist>>,
  TError,
  { token: string; itemId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteWishedVariantFromWishlist>>,
    { token: string; itemId: string }
  > = (props) => {
    const { token, itemId } = props ?? {};

    return deleteWishedVariantFromWishlist(token, itemId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteWishedVariantFromWishlistMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteWishedVariantFromWishlist>>
>;

export type DeleteWishedVariantFromWishlistMutationError = ForbiddenResponse;

/**
 * @summary Delete Item from Wishlist
 */
export const useDeleteWishedVariantFromWishlist = <
  TError = ForbiddenResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteWishedVariantFromWishlist>>,
    TError,
    { token: string; itemId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteWishedVariantFromWishlist>>,
  TError,
  { token: string; itemId: string },
  TContext
> => {
  const mutationOptions = getDeleteWishedVariantFromWishlistMutationOptions(options);

  return useMutation(mutationOptions);
};
