/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Storefront API
 * Storefront API is a modern REST API based on the [JSON API spec](https://jsonapi.org/) which provides you with all the necessary endpoints to build amazing user intefaces either in JavaScript frameworks or native mobile libraries.

Download [official JavaScript & TypeScript SDK](https://github.com/spree/spree-storefront-api-v2-js-sdk)

Import to [Postman](https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml)
 * OpenAPI spec version: 2.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  NotFoundResponse,
  ProductListResponse,
  ProductResponse,
  ProductsListParams,
  ShowProductParams
} from '.././schema';
import { customInstance } from '../../../config/custom-instance';

/**
 * Returns a list of products for the current Store.
 * @summary List all Products
 */
export const productsList = (params?: ProductsListParams, signal?: AbortSignal) => {
  return customInstance<ProductListResponse>({
    url: `/api/v2/storefront/products`,
    method: 'GET',
    params,
    signal
  });
};

export const getProductsListQueryKey = (params?: ProductsListParams) => {
  return [`/api/v2/storefront/products`, ...(params ? [params] : [])] as const;
};

export const getProductsListQueryOptions = <
  TData = Awaited<ReturnType<typeof productsList>>,
  TError = unknown
>(
  params?: ProductsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof productsList>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProductsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof productsList>>> = ({ signal }) =>
    productsList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof productsList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ProductsListQueryResult = NonNullable<Awaited<ReturnType<typeof productsList>>>;
export type ProductsListQueryError = unknown;

/**
 * @summary List all Products
 */
export const useProductsList = <TData = Awaited<ReturnType<typeof productsList>>, TError = unknown>(
  params?: ProductsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof productsList>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getProductsListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getProductsListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof productsList>>,
  TError = unknown
>(
  params?: ProductsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsList>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProductsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof productsList>>> = ({ signal }) =>
    productsList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof productsList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ProductsListSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof productsList>>>;
export type ProductsListSuspenseQueryError = unknown;

/**
 * @summary List all Products
 */
export const useProductsListSuspense = <
  TData = Awaited<ReturnType<typeof productsList>>,
  TError = unknown
>(
  params?: ProductsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsList>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getProductsListSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Returns Product details. You can use product permalink:

```
GET /api/v2/storefront/products/knitted-high-neck-sweater
```

Or Product ID:

```
GET /api/v2/storefront/products/21
```

**Note** API will attempt a permalink lookup before an ID lookup.
 * @summary Retrieve a Product
 */
export const showProduct = (
  productSlug: string,
  params?: ShowProductParams,
  signal?: AbortSignal
) => {
  return customInstance<ProductResponse>({
    url: `/api/v2/storefront/products/${productSlug}`,
    method: 'GET',
    params,
    signal
  });
};

export const getShowProductQueryKey = (productSlug: string, params?: ShowProductParams) => {
  return [`/api/v2/storefront/products/${productSlug}`, ...(params ? [params] : [])] as const;
};

export const getShowProductQueryOptions = <
  TData = Awaited<ReturnType<typeof showProduct>>,
  TError = NotFoundResponse
>(
  productSlug: string,
  params?: ShowProductParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof showProduct>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShowProductQueryKey(productSlug, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showProduct>>> = ({ signal }) =>
    showProduct(productSlug, params, signal);

  return { queryKey, queryFn, enabled: !!productSlug, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof showProduct>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShowProductQueryResult = NonNullable<Awaited<ReturnType<typeof showProduct>>>;
export type ShowProductQueryError = NotFoundResponse;

/**
 * @summary Retrieve a Product
 */
export const useShowProduct = <
  TData = Awaited<ReturnType<typeof showProduct>>,
  TError = NotFoundResponse
>(
  productSlug: string,
  params?: ShowProductParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof showProduct>>, TError, TData>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShowProductQueryOptions(productSlug, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getShowProductSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof showProduct>>,
  TError = NotFoundResponse
>(
  productSlug: string,
  params?: ShowProductParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof showProduct>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShowProductQueryKey(productSlug, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showProduct>>> = ({ signal }) =>
    showProduct(productSlug, params, signal);

  return { queryKey, queryFn, enabled: !!productSlug, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof showProduct>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShowProductSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof showProduct>>>;
export type ShowProductSuspenseQueryError = NotFoundResponse;

/**
 * @summary Retrieve a Product
 */
export const useShowProductSuspense = <
  TData = Awaited<ReturnType<typeof showProduct>>,
  TError = NotFoundResponse
>(
  productSlug: string,
  params?: ShowProductParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof showProduct>>, TError, TData>
    >;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShowProductSuspenseQueryOptions(productSlug, params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
